'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const M=require('../../src/desktop-refinement-models.js'),T=require('../../src/theme-models.js');
function art(profile='windows',family='auto'){
    const OS={themes:{artwork:{profile,family}},apps:new Map(),esc:s=>String(s).replace(/[&<>"']/g,c=>'&#'+c.charCodeAt(0)+';'),icon:()=>'<svg viewBox="0 0 24 24"><path d="M4 5h16v14H4z"/></svg>',on(){}};
    vm.runInNewContext(fs.readFileSync('src/profile-artwork.js','utf8'),{Aster:OS,console,Map,Object,String,Math,Number});return OS;
}
test('All three default profiles select original profile-specific icon geometry',()=>{const samples=['windows','macos26','ubuntu'].map(p=>art(p).visualIcon('files',48));assert.equal(new Set(samples).size,3);for(const[p,i]of ['windows','macos26','ubuntu'].entries())assert(samples[p].includes('data-icon-family="'+i+'"'));});
test('Each family renders 29 distinct original symbols without shared IDs or active content',()=>{for(const family of ['windows','macos26','ubuntu','prism']){const OS=art('windows',family),samples=OS.iconArtwork.builtins.map(id=>OS.visualIcon(id,48));assert.equal(new Set(samples).size,29);for(const s of samples)assert(!/\sid=|<image|<use|<script|<foreignObject|https?:|\son\w+=/i.test(s));}});
test('Caller sizes and IDs remain bounded and escaped for all families',()=>{for(const family of ['windows','macos26','ubuntu','prism']){const OS=art('windows',family);for(const n of [0,-1,Infinity,NaN,1e9,'42px;overflow:visible']){const s=OS.visualIcon('<script>"',n);assert(!s.includes('<script>'));const size=+s.match(/--icon-size:([\d.]+)/)[1];assert(size>=8&&size<=128);}}});
test('Cache keys include family and bounded cache reuses recently used entries',()=>{const OS=art();const first=OS.visualIcon('files');OS.themes.artwork.profile='ubuntu';assert.notEqual(first,OS.visualIcon('files'));for(let i=0;i<400;i++)OS.visualIcon('custom'+i);assert.equal(OS.iconArtwork.cacheSize,256);});
test('Windows and GNOME use varied object silhouettes instead of a universal badge',()=>{for(const family of ['windows','ubuntu']){const OS=art(family),d=OS.iconArtwork.builtins.map(id=>OS.visualIcon(id).match(/class="art-plate" d="([^"]+)"/)[1]);assert(new Set(d).size>=7);}});
test('Theme normalization validates icon family and keeps old themes following their desktop',()=>{assert.equal(T.normalize({}).iconFamily,'auto');for(const s of ['auto','windows','macos26','ubuntu','prism'])assert.equal(T.normalize({iconFamily:s}).iconFamily,s);assert.equal(T.normalize({iconFamily:'url(https://bad)'}).iconFamily,'auto');});
test('Portable descriptors and merge preserve an explicit family without resetting optics',()=>{const t=T.merge(T.normalize({profile:'macos26',optics:{bend:80}}),{iconFamily:'ubuntu'});assert.equal(t.iconFamily,'ubuntu');assert.equal(T.normalize(JSON.parse(JSON.stringify(t))).iconFamily,'ubuntu');assert.equal(t.optics.bend,80);});
test('Quick Preview accepts only bounded virtual paths, not host mounts or traversal',()=>{assert(M.virtualPath('/Documents/one file.txt'));for(const p of ['/Local/data/a','/.Trash/a','/Documents/../x','//x','/x\\y','/x\0a','https://a/','/','/x/'.repeat(700)])assert(!M.virtualPath(p),p);});
test('Active documents always become inert text, not rendered executable markup',()=>{for(const ext of ['html','svg','js','mjs','py','theme'])assert.equal(M.previewKind('/x.'+ext,'application/octet-stream'),'text');assert.equal(M.previewKind('/app.exe','application/x-msdownload'),'metadata');});
test('Preview media kinds are fixed and unknown types remain metadata-only',()=>{assert.equal(M.previewKind('/a.png'),'image');assert.equal(M.previewKind('/a.wav'),'audio');assert.equal(M.previewKind('/a.webm'),'video');assert.equal(M.previewKind('/a.bin'),'metadata');assert.equal(M.TEXT_LIMIT,131072);assert.equal(M.PREVIEW_LIMIT,16777216);});
test('Pin ordering is immutable, deduplicates, and preserves the other application IDs',()=>{const a=['files','terminal','notepad'];assert.deepEqual(M.reorderPins(a,'notepad','files'),['notepad','files','terminal']);assert.deepEqual(a,['files','terminal','notepad']);assert.deepEqual(M.reorderPins(a,'files','files'),a);});
test('Unpinned or oversize pin operations reject without adding applications',()=>{assert.throws(()=>M.reorderPins(['a'],'b','a'));assert.throws(()=>M.reorderPins(Array(300).fill('a'),'a','a'));assert.throws(()=>M.reorderPins(['a'],null,'a'));});
const windows=[{id:'a',desktop:'one',minimized:false,stackOrder:10},{id:'b',desktop:'one',minimized:true,stackOrder:11},{id:'c',desktop:'two',minimized:false,stackOrder:12}];
test('Show Desktop records only visible windows on the active desktop',()=>{assert.deepEqual(M.desktopPlan(windows,'one'),{action:'hide',ids:['a'],focused:null});});
test('Desktop restore never crosses desktops or restores previously minimized windows',()=>{const all=windows.map(w=>({...w,minimized:true}));assert.deepEqual(M.desktopPlan(all,'two',{ids:['a','c'],focused:'a'}),{action:'restore',ids:['c'],focused:'c'});});
test('Closed, moved and manually restored snapshot members are safe to skip',()=>{const all=[{...windows[0],closed:true},{...windows[1],desktop:'two'},{...windows[2],desktop:'one',minimized:false}];assert.deepEqual(M.desktopPlan(all,'one',{ids:['a','b','c'],focused:'a'}),{action:'restore',ids:[],focused:null});});
test('Static, standalone and service worker include all new modules',()=>{for(const name of ['src/desktop-refinement.js','src/desktop-refinement-models.js','src/desktop-refinement.css']){for(const entry of ['index.html','sw.js'])assert(fs.readFileSync(entry,'utf8').includes(name));assert(fs.readFileSync('Aster.html','utf8').includes(fs.readFileSync(name,'utf8').slice(0,80)));}});
