'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const read=n=>fs.readFileSync(n,'utf8');
function artwork(){const OS={apps:new Map(),esc:s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),icon:()=>'<svg viewBox="0 0 24 24"><path d="M4 4h16v16H4z"/></svg>'};vm.runInNewContext(read('src/profile-artwork.js'),{Aster:OS,console,Map,Object,String,Math,Number});return OS;}
function windows(){const doc={addEventListener(){},body:{},activeElement:null},OS={$:()=>({hidden:true,children:[]}),windows:new Map(),on:()=>()=>{},emit(){},db:{set(){}},renderer:{invalidate(){},removeSurface(){}},uid:()=> 'test'};vm.runInNewContext(read('src/windows.js'),{Aster:OS,window:{addEventListener(){}},document:doc,console,setTimeout:()=>1,clearTimeout(){}});return OS;}
test('Original artwork provides 29 owned, unique symbols with deterministic rendering',()=>{const OS=artwork(),all=OS.iconArtwork.builtins.map(id=>OS.visualIcon(id,32));assert.equal(all.length,29);assert.equal(new Set(all).size,29);for(const id of OS.iconArtwork.builtins)assert.equal(OS.visualIcon(id,32),OS.visualIcon(id,32));});
test('Artwork contains no native platform variants or executable/external resources',()=>{const OS=artwork();for(const id of OS.iconArtwork.builtins){const s=OS.visualIcon(id);assert(!/<(?:image|use|script|foreignObject)\b|\sid=|\bon\w+=|https?:|art-(?:macos|windows|ubuntu)/i.test(s));assert(s.includes('art-plate')&&s.includes('art-glyph')&&s.includes('art-signature'));}});
test('Caller size is finite, clamped and never inserted as arbitrary CSS',()=>{const OS=artwork();for(const size of [NaN,Infinity,-1,0,10000,'32px;position:fixed','" onload="bad']){const s=OS.visualIcon('files',size),n=Number(s.match(/--icon-size:([\d.]+)px/)[1]);assert(n>=8&&n<=128);assert(!s.includes('onload')&&!s.includes('position:fixed'));}});
test('Unknown app IDs are escaped and still get fallback artwork',()=>{const OS=artwork(),s=OS.visualIcon('<script>"hello</script>');assert(!s.includes('<script>'));assert(s.includes('&lt;script&gt;'));assert(s.includes('art-glyph'));});
test('Icon cache has a hard upper bound independent of application count',()=>{const OS=artwork();for(let i=0;i<2000;i++)OS.visualIcon('app-'+i,32);assert.equal(OS.iconArtwork.cacheSize,256);});
test('The caption layer is explicitly above the glass foreground with larger macOS targets',()=>{const css=read('src/ui-refinement.css');assert(css.includes('.titlebar>.window-controls{z-index:5'));assert(css.includes('.titlebar>.window-title{pointer-events:none}'));assert(css.includes('width:26px;min-width:26px;height:26px'));assert(css.includes('@media(pointer:coarse)'));assert(css.includes('[data-window-action=close]'));});
test('Normal and always-on-top order stay separated after focus changes',()=>{const OS=windows(),proto=OS.DesktopWindow.prototype;for(const z of [10,999,8999]){const w=Object.assign(Object.create(proto),{z,alwaysOnTop:false});assert.equal(w.stackOrder,z);w.alwaysOnTop=true;assert.equal(w.stackOrder,10000+z);}});
test('Pin state only accepts a boolean and updates the stored session state',()=>{const OS=windows(),w=Object.assign(Object.create(OS.DesktopWindow.prototype),{state:{},sync(){},closed:false});w.setAlwaysOnTop(true);assert(w.alwaysOnTop&&w.state.alwaysOnTop);w.setAlwaysOnTop('true');assert(!w.alwaysOnTop&&!w.state.alwaysOnTop);});
test('Concurrent dirty close requests share one prompt and cancellation preserves window',async()=>{const OS=windows();let calls=0,resolve;const w=Object.assign(Object.create(OS.DesktopWindow.prototype),{closed:false,beforeClose:()=>{calls++;return new Promise(r=>resolve=r);}});const a=w.close(),b=w.close();await Promise.resolve();assert.equal(calls,1);resolve(false);assert.equal(await a,false);assert.equal(await b,false);assert(!w.closed);assert.equal(w.closePending,null);});
test('Confirmation exceptions clear the guard so close can be tried again',async()=>{const OS=windows();let calls=0;const w=Object.assign(Object.create(OS.DesktopWindow.prototype),{closed:false,beforeClose:()=>{calls++;throw Error('confirmation failed');}});await assert.rejects(w.close(),/confirmation failed/);assert.equal(w.closePending,null);await assert.rejects(w.close(),/confirmation failed/);assert.equal(calls,2);});
test('Center respects the current theme work area without changing window dimensions',()=>{const OS=windows();OS.viewport=()=>({w:1000,h:720});const w=Object.assign(Object.create(OS.DesktopWindow.prototype),{rect:{x:30,y:70,w:500,h:400},sync(){},focus(){},closed:false,maximized:false});w.center();assert.deepEqual(w.rect,{x:250,y:160,w:500,h:400});});
test('Rebuilt static/standalone/cache all include the UI fix and original artwork',()=>{for(const name of ['src/ui-refinement.css','src/profile-artwork.js']){assert(read('index.html').includes(name));assert(read('sw.js').includes(name));assert(read('Aster.html').includes(read(name).slice(0,90)));}});
test('Closing Run releases its dialog guard while an earlier launch is still pending',async()=>{
    // Execute the actual production dialog method. Only DOM and async launch
    // dependencies are controlled here; the inherited browser suite uses real apps.
    const source=read('src/shell-launch.js'),start=source.indexOf('    OS.showRun=async'),end=source.indexOf('    OS.shellLaunch=',start);
    let resolveLaunch,launchCalls=0;const launching=new Promise(r=>resolveLaunch=r),dialogs=[];
    const input={value:'calc',setAttribute(){},focus(){},select(){}},yes={addEventListener(){}};
    const dialog={querySelector:q=>q==='input'?input:yes},OS={apps:new Map(),closePanels(){},guard:f=>f,
        el:()=>({append(){},setAttribute(){}}),dialog:()=>new Promise(resolve=>dialogs.push(resolve))};
    vm.runInNewContext('let runOpen=false;'+source.slice(start,end),{OS,$:()=>dialog,state:{runHistory:[]},note:()=>null,button:()=>null,M:{parseRun(){}},executeRun:()=>{launchCalls++;return launching;}});
    const first=OS.showRun();await OS.showRun();assert.equal(dialogs.length,1,'Only one dialog may be open');
    dialogs[0]('calc');await Promise.resolve();await Promise.resolve();assert.equal(launchCalls,1);
    const next=OS.showRun();assert.equal(dialogs.length,2,'A completed dialog must not stay locked by slow launch/history persistence');
    dialogs[1](null);await next;resolveLaunch('application');assert.equal(await first,'application');
    const third=OS.showRun();assert.equal(dialogs.length,3);dialogs[2](null);await third;
});
