'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const M=require('../../src/file-picker-models.js');
const file=(name,size=0,modified=0)=>({path:'/Documents/'+name,kind:'file',size,modified});
const folder=name=>({path:'/Documents/'+name,kind:'directory'});
test('invalid preferences normalize without retaining arbitrary keys',()=>assert.deepEqual(M.preferences({view:'evil',sort:'constructor',ascending:0,hidden:1,preview:'yes',other:1}),M.DEFAULTS));
test('preferences accept null and preserve explicit supported choices',()=>{assert.deepEqual(M.preferences(null),M.DEFAULTS);assert.equal(M.preferences({view:'grid',ascending:false,hidden:true}).view,'grid');});
test('natural numeric ordering is case-insensitive',()=>assert.deepEqual(M.ordered([file('a10.txt'),file('A2.txt'),file('a1.txt')],{}).map(r=>M.name(r.path)),['a1.txt','A2.txt','a10.txt']));
test('folders precede files in both directions',()=>{for(const ascending of [true,false])assert.equal(M.ordered([file('a'),folder('z')],{ascending})[0].kind,'directory');});
test('sorting numeric sizes and modified dates has deterministic name ties',()=>{const rows=[file('b',3,1),file('a',3,2),file('c',9,3)];assert.equal(M.name(M.ordered(rows,{sort:'size'})[0].path),'a');assert.equal(M.name(M.ordered(rows,{sort:'modified',ascending:false})[0].path),'c');});
test('filtering neither mutates rows nor shows hidden entries by default',()=>{const rows=[file('.secret'),file('hello.txt')];assert.equal(M.ordered(rows,{}).length,1);assert.equal(rows.length,2);assert.equal(M.ordered(rows,{hidden:true},'SECRET').length,1);});
test('Unicode canonical search and spaces remain intact',()=>assert.equal(M.ordered([file('café notes.txt')],{},'cafe\u0301').length,1));
test('file kinds handle extensionless names and case',()=>{assert.equal(M.type(file('README')),'File');assert.equal(M.type(file('PHOTO.PNG')),'PNG image');assert.equal(M.type(folder('x.txt')),'Folder');});
test('breadcrumbs preserve exact path components without HTML interpolation',()=>assert.deepEqual(M.breadcrumbs('/Documents/<unsafe>/日本語'),[{path:'/',name:'Aster'},{path:'/Documents',name:'Documents'},{path:'/Documents/<unsafe>',name:'<unsafe>'},{path:'/Documents/<unsafe>/日本語',name:'日本語'}]));
test('single and folder selections replace old selection',()=>{const rows=[folder('x'),file('a'),file('b')];assert.deepEqual([...M.select(rows,new Set(['/Documents/a']),'/Documents/x',null,{multiple:true,toggle:true})],['/Documents/x']);});
test('Ctrl toggles files and Shift selects only files in the range',()=>{const rows=[folder('z'),file('a'),file('b'),file('c')];assert.deepEqual([...M.select(rows,new Set(),'/Documents/c','/Documents/z',{multiple:true,range:true})],['/Documents/a','/Documents/b','/Documents/c']);assert.equal(M.select(rows,new Set(['/Documents/a']),'/Documents/a',null,{multiple:true,toggle:true}).size,0);});
test('history truncates forward entries after new navigation',()=>{const h=new M.History('/');h.commit('/a');h.commit('/b');h.commit('/a',1);assert.equal(h.forward,true);h.commit('/c');assert.deepEqual(h.paths,['/','/a','/c']);});
test('history is bounded to 50 committed locations',()=>{const h=new M.History('/');for(let i=0;i<70;i++)h.commit('/'+i);assert.equal(h.paths.length,50);assert.equal(h.index,49);assert.equal(h.target(-1),'/68');assert.equal(h.target(1),undefined);});
test('unknown selection cannot retain a stale path',()=>assert.equal(M.select([file('a')],new Set(['/Documents/old']),'/Documents/nope',null,{multiple:true}).size,0));

test('deselecting one of two files retains the other exact path',()=>{const rows=[file('a'),file('b')];assert.deepEqual([...M.select(rows,new Set(['/Documents/a','/Documents/b']),'/Documents/a','/Documents/b',{multiple:true,toggle:true})],['/Documents/b']);});
