'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('src/integrated-desktop.js','utf8');
function models(){
 const apps=new Map(['snips','clock','clipboard','focus','widgets','workspaces','history','storage','accessibility','recorder','archives'].map(id=>[id,{id,title:id,mount(){}}]));
 const context=vm.createContext({Aster:{apps,settings:{},$:()=>null,fs:{parent:p=>p.slice(0,p.lastIndexOf('/'))||'/'},on(){},openPath(){}},document:{body:{classList:{toggle(){},add(){}}}},Object,Promise,Set,console});
 vm.runInContext(source,context);return context.Aster;
}
test('Legacy utility descriptors are hidden but retained for API compatibility',()=>{const m=models();for(const id of Object.keys(m.integratedFeatures))assert.equal(m.apps.get(id).hidden,true);assert.notEqual(m.apps.get('snips').hidden,true);});
test('Session migration routes old utilities to natural persistent parents',()=>{const m=models();for(const [app,target,section]of [['storage','settings','storage'],['accessibility','settings','accessibility'],['history','settings','recovery']]){const input={app,state:{path:'/Documents/item.txt'},rect:{x:20,y:30,w:400,h:500}};const result=m.migrateShellSession(input);assert.equal(result.app,target);assert.equal(result.state.section,section);assert.equal(result.rect,input.rect);assert.equal(input.app,app);assert.equal(input.state.section,undefined);}});
test('Transient flyouts never restore as orphan utility windows',()=>{const m=models();for(const app of ['clipboard','widgets','workspaces'])assert.equal(m.migrateShellSession({app}),null);assert.equal(m.migrateShellSession(null),null);});
test('Old Focus and recording windows migrate without starting an operation',()=>{const m=models();assert.equal(m.migrateShellSession({app:'focus'}).state.mode,'focus');assert.equal(m.migrateShellSession({app:'recorder'}).app,'snips');assert.equal(m.migrateShellSession({app:'recorder'}).state.mode,'record');assert.equal(m.migrateShellSession({app:'archives',state:{path:'/Downloads/X.zip'}}).state.path,'/Downloads');});
test('Native app state and file views survive session migration without mutation',()=>{const m=models(),input={app:'notepad',state:{path:'/Documents/a.txt'},desktop:'desk-1'};const result=m.migrateShellSession(input);assert.equal(result.app,'notepad');assert.equal(result.state.path,input.state.path);assert.notEqual(result.state,input.state);});
test('Integrated styles and modules are included in source, standalone and offline assets',()=>{const index=fs.readFileSync('index.html','utf8'),offline=fs.readFileSync('sw.js','utf8'),standalone=fs.readFileSync('Aster.html','utf8');for(const file of ['integrated-desktop.js','shell-experience.js','shell-design.css']){assert.ok(index.includes('src/'+file));assert.ok(offline.includes('src/'+file));}assert.ok(index.indexOf('integrated-desktop.js')<index.indexOf('src/shell.js'));assert.ok(index.indexOf('src/shell.js')<index.indexOf('shell-experience.js'));assert.ok(standalone.includes('OS.migrateShellSession'));assert.ok(!standalone.includes('href="src/shell-design.css"'));});
test('Settings hierarchy contains actual destination pages and no utility hub',()=>{const m=models();const rows=m.integrations.navigation;assert.equal(rows.find(r=>r[0]==='storage')[4],'system');assert.equal(rows.find(r=>r[0]==='clipboard')[4],'system');assert.equal(rows.find(r=>r[0]==='recovery')[4],'system');assert.equal(rows.some(r=>r[0]==='essentials'),false);assert.equal(m.integrations.normalize('essentials'),'system');});
test('DOM factory preserves true and false for enumerated drag/edit attributes',()=>{const core=fs.readFileSync('src/core.js','utf8'),start=core.indexOf('    OS.el ='),end=core.indexOf('    OS.formatBytes',start);const context=vm.createContext({OS:{},document:{createElement(){return {attrs:{},setAttribute(k,v){this.attrs[k]=v;},append(){},addEventListener(){}};},createTextNode:s=>s}});vm.runInContext(core.slice(start,end),context);for(const name of ['draggable','contenteditable','spellcheck'])for(const value of [true,false])assert.equal(context.OS.el('div',{[name]:value}).attrs[name],String(value));assert.equal(context.OS.el('button',{disabled:true}).attrs.disabled,'');assert.equal(context.OS.el('button',{disabled:false}).attrs.disabled,undefined);});
