/* Resource, registry, USER32 and GDI contracts. The WineMine integration executes
 * the upstream app's actual PE32 instructions; unit helpers also isolate APIs. */
'use strict';
const fs=require('node:fs'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const{root,wasm,Runtime,u32}=require('./runner.cjs');const W=globalThis.AsterWin32;
const exe=fs.readFileSync(root+'/src/win32/third-party/winemine.exe');
const report={tests:[],environment:{node:process.version,platform:process.platform},fixtureSha256:crypto.createHash('sha256').update(exe).digest('hex')};
let compiled;
async function runtime(host){compiled||=await WebAssembly.compile(wasm);const r=await Runtime.create(compiled,host);r.load(exe,'winemine.exe');return r;}
const api=(r,dll,name,...args)=>{const a=r.apis.get(dll+'.dll!'+name);assert(a,'Missing API '+dll+'!'+name);return a.fn(...args);};
const U=(r,n,...a)=>api(r,'user32',n,...a),G=(r,n,...a)=>api(r,'gdi32',n,...a),K=(r,n,...a)=>api(r,'kernel32',n,...a),R=(r,n,...a)=>api(r,'advapi32',n,...a);
async function check(name,fn){const start=performance.now();try{const detail=await fn();report.tests.push({name,status:'PASS',ms:performance.now()-start,detail});console.log('PASS',name);}catch(e){report.tests.push({name,status:'FAIL',error:e.stack});console.error('FAIL',name,e.stack);process.exitCode=1;}}
function header(r,w,h,bits=32){const p=r.mem.alloc(1100);r.mem.w32(p,40);r.mem.w32(p+4,w);r.mem.w32(p+8,h);r.mem.w16(p+12,1);r.mem.w16(p+14,bits);return p;}
function regkey(r,path='Software\\AsterTest',access=0x3f,options=0){const p=r.mem.alloc(4);assert.equal(R(r,'RegCreateKeyExW',0x80000001,r.mem.str(path,true),0,0,options,access,0,p,0),0);return r.mem.u32(p);}
const rgba=(r,b)=>[...r.bitmapObject(b).pixels];
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function wait(fn,ms=3000){const end=performance.now()+ms;while(!fn()){if(performance.now()>end)throw Error('Runtime condition timed out');await delay(3);}}
class Writer{constructor(){this.a=[];}u16(n){this.a.push(n&255,n>>>8&255);return this;}u32(n){this.a.push(...u32(n));return this;}str(s){for(const c of s)this.u16(c.charCodeAt(0));return this.u16(0);}align(){while(this.a.length%4)this.a.push(0);return this;}name(n){return typeof n==='number'?this.u16(65535).u16(n):this.str(n);}put(r){const p=r.mem.alloc(this.a.length);r.mem.copy(p,Uint8Array.from(this.a));return[p,this.a.length];}}
function dialogFixture(extended){const b=new Writer();if(extended)b.u16(1).u16(65535).u32(0).u32(0).u32(0x40).u16(2);else b.u32(0x40).u32(0).u16(2);b.u16(0).u16(0).u16(100).u16(60).name('').name('').str('Dialog');b.u16(8);if(extended)b.u16(400).u16(0x100);b.str('Sans');
 for(let i=0;i<2;i++){b.align();if(extended)b.u32(0).u32(0).u32(0x50010000);else b.u32(0x50010000).u32(0);b.u16(2).u16(i*20).u16(40).u16(12);if(extended)b.u32(0x10000+i);else b.u16(100+i);b.name(0x81).name('Text');b.u16(i?0:extended?1:3);if(!i)b.a.push(0x42);}return b;}
(async()=>{
await check('PE resource strings, named modules and pointer-return LoadStringW',async()=>{const r=await runtime(),m=r.mem,p=m.alloc(80),out=m.alloc(4);assert.equal(U(r,'LoadStringW',0,1101,p,40),8);assert.equal(m.string(p,true),'WineMine');assert.equal(U(r,'LoadStringW',r.image.base,1101,out,0),8);assert.equal(m.string(m.u32(out),true,8),'WineMine');assert.equal(U(r,'LoadStringA',0,1101,p,5),4);assert.equal(m.string(p),'Wine');assert.equal(U(r,'LoadStringW',0,9999,p,40),0);assert.equal(r.lastError,1814);});
await check('FindResource/LoadResource/LockResource expose only mapped resource bytes',async()=>{const r=await runtime(),h=K(r,'FindResourceW',0,4,2),p=K(r,'LoadResource',0,h);assert(h);assert.equal(K(r,'LockResource',p),p);assert.equal(K(r,'SizeofResource',0,h),2152);assert.equal(K(r,'LoadResource',0x123456,h),0);assert.equal(K(r,'LockResource',p+1),0);assert.equal(K(r,'FindResourceExW',0,2,4,0x999),h);});
await check('Actual MENU, dialog and accelerator resources retain IDs and labels',async()=>{const r=await runtime(),menu=r.resource(0,4,1),items=W.parseMenu(r.mem,menu.address,menu.size);assert.equal(items[0].text,'&Game');assert(items[0].children.some(i=>i.id===1008&&i.text==='&Custom...'));const res=r.resource(0,5,3),d=W.parseDialog(r.mem,res.address,res.size);assert.equal(d.title,'Custom Game');assert.deepEqual(d.controls.filter(c=>c.className===0x81).map(c=>c.id),[1032,1031,1033]);const h=U(r,'LoadAcceleratorsW',0,1201);assert.deepEqual(r.handles.get(h).items,[{flags:1,key:113,id:1001}]);});
await check('Resource directory cycles are rejected before host allocations',async()=>{const r=await runtime(),base=r.image.base+r.image.resources.rva;r.mem.w32(base+20,0x80000000);assert.throws(()=>new W.ResourceIndex(r.image,r.mem),/Cyclic|overdeep/);});
await check('Resource directory tables cannot run beyond their advertised size',async()=>{const r=await runtime();assert.throws(()=>new W.ResourceIndex({...r.image,resources:{rva:r.image.resources.rva,size:17}},r.mem),/bounds/);});
await check('Resource leaves cannot reference unmapped guest data',async()=>{const r=await runtime(),m=r.mem,base=r.image.base+r.image.resources.rva;let at=base;for(let depth=0;depth<3;depth++){const child=m.u32(at+20);if(child&0x80000000)at=base+(child&0x7fffffff);else{m.w32(base+child,0x3000000);break;}}assert.throws(()=>new W.ResourceIndex(r.image,m),/mapped PE section/);});
for(const extended of [false,true])await check((extended?'DIALOGEX':'DIALOG')+' template alignment and creation data lengths',async()=>{const r=await runtime(),b=dialogFixture(extended),[p,n]=b.put(r),d=W.parseDialog(r.mem,p,n);assert.equal(d.extended,extended);assert.equal(d.controls[0].creationBytes,1);assert.equal(r.mem.u8(d.controls[0].creationData),0x42);assert.equal(d.controls[1].id,extended?0x10001:101);assert.throws(()=>W.parseDialog(r.mem,p,n-1),/Truncated/);});
await check('MENUEX preserves command IDs, check state and nested alignment',async()=>{const r=await runtime(),b=new Writer().u16(1).u16(4).u32(0);b.u32(0).u32(0).u32(9).u16(0x81).str('Menu').align().u32(0);b.u32(0).u32(8).u32(4001).u16(0x80).str('Command');const [p,n]=b.put(r),menu=W.parseMenu(r.mem,p,n);assert.equal(menu[0].children[0].id,4001);assert.equal(menu[0].children[0].state,8);assert.throws(()=>W.parseMenu(r.mem,p,n-2),/Truncated/);});
await check('Oversized dialog counts and unterminated menu strings fail boundedly',async()=>{const r=await runtime(),b=dialogFixture(false),[p,n]=b.put(r);r.mem.w16(p+8,129);assert.throws(()=>W.parseDialog(r.mem,p,n),/control limit/);const q=r.mem.alloc(8);r.mem.w16(q+4,0x80);r.mem.w16(q+6,1);assert.throws(()=>W.parseMenu(r.mem,q,8),/Truncated/);});
await check('Registry is private, case-insensitive and reports create disposition',async()=>{const r=await runtime(),m=r.mem,h=regkey(r),p=m.alloc(4),disp=m.alloc(4);assert.equal(R(r,'RegCreateKeyExW',0x80000001,m.str('software\\astertest',true),0,0,0,1,0,p,disp),0);assert.equal(m.u32(disp),2);const other=await runtime();assert.equal(R(other,'RegOpenKeyExW',0x80000001,other.mem.str('Software\\AsterTest',true),0,1,other.mem.alloc(4)),2);assert.equal(R(r,'RegCloseKey',h),0);assert.equal(R(r,'RegCloseKey',h),6);});
await check('Registry DWORD sizing leaves an undersized buffer untouched',async()=>{const r=await runtime(),m=r.mem,h=regkey(r),name=m.str('Number',true),value=m.alloc(4),size=m.alloc(4),out=m.alloc(16),type=m.alloc(4);m.w32(value,42);assert.equal(R(r,'RegSetValueExW',h,name,0,4,value,4),0);m.w32(size,3);m.w32(out,0xcccccccc);assert.equal(R(r,'RegQueryValueExW',h,name,0,type,out,size),234);assert.equal(m.u32(size),4);assert.equal(m.u32(out),0xcccccccc);assert.equal(m.u32(type),4);m.w32(size,16);assert.equal(R(r,'RegQueryValueExW',h,m.str('NUMBER',true),0,type,out,size),0);assert.equal(m.u32(out),42);});
await check('Registry ANSI strings convert to UTF-16 and default values persist exactly',async()=>{const r=await runtime(),m=r.mem,h=regkey(r),value=m.str('caf\u00e9'),size=m.alloc(4),out=m.alloc(32);assert.equal(R(r,'RegSetValueExA',h,0,0,1,value,5),0);m.w32(size,32);assert.equal(R(r,'RegQueryValueExW',h,0,0,0,out,size),0);assert.equal(m.u32(size),10);assert.equal(m.string(out,true),'caf\u00e9');const other=await runtime();other.importRegistry(r.exportRegistry());const key=regkey(other);other.mem.w32(size,32);assert.equal(R(other,'RegQueryValueExA',key,0,0,0,out,size),0);assert.equal(other.mem.string(out),'caf\u00e9');});
await check('Registry access masks deny mutation through a query-only handle',async()=>{const r=await runtime(),m=r.mem,h=regkey(r,'Software\\ReadOnly',1),name=m.str('Value',true),value=m.alloc(4);assert.equal(R(r,'RegSetValueExW',h,name,0,4,value,4),5);assert.equal(R(r,'RegDeleteValueW',h,name),5);assert.equal(R(r,'RegCreateKeyExW',h,m.str('Child',true),0,0,0,1,0,m.alloc(4),0),5);});
await check('Volatile registry branches are never exported',async()=>{const r=await runtime();regkey(r,'Software');regkey(r,'Software\\Transient',0x3f,1);regkey(r,'Software\\Transient\\Child');regkey(r,'Software\\Permanent');const snapshot=r.exportRegistry();assert(!snapshot.keys.some(k=>k.path.includes('transient')));assert(snapshot.keys.some(k=>k.path.endsWith('permanent')));});
await check('Registry snapshot import is transactional and canonical',async()=>{const r=await runtime();regkey(r);const before=r.exportRegistry();for(const path of ['hkcu\\\\bad','hkcu\\bad\\','bogus','HKCU']){const bad={version:1,keys:[{path,name:'bad',values:[]}]};assert.throws(()=>r.importRegistry(bad),/registry|Registry/);assert.deepEqual(r.exportRegistry(),before);}const bad=structuredClone(before);bad.keys.at(-1).values.push({name:'bad',type:4,bytes:new Uint8Array(3)});assert.throws(()=>r.importRegistry(bad),/value snapshot/);assert.deepEqual(r.exportRegistry(),before);});
await check('Registry value enumeration reports lengths, then stops with NO_MORE_ITEMS',async()=>{const r=await runtime(),m=r.mem,h=regkey(r),p=m.str('x'),size=m.alloc(4),n=m.alloc(4),name=m.alloc(32),data=m.alloc(32),type=m.alloc(4);R(r,'RegSetValueExA',h,p,0,3,p,1);m.w32(n,16);m.w32(size,32);assert.equal(R(r,'RegEnumValueW',h,0,name,n,0,type,data,size),0);assert.equal(m.string(name,true),'x');assert.equal(m.u32(n),1);assert.equal(m.u32(size),1);assert.equal(m.u8(data),120);assert.equal(R(r,'RegEnumValueW',h,1,name,n,0,type,data,size),259);});
await check('Registry non-recursive deletion preserves descendants; DeleteTree removes them',async()=>{const r=await runtime(),m=r.mem,h=regkey(r);regkey(r,'Software\\AsterTest\\Child');assert.equal(R(r,'RegDeleteKeyW',0x80000001,m.str('Software\\AsterTest',true)),5);assert.equal(R(r,'RegDeleteTreeW',h,m.str('Child',true)),0);assert.equal(R(r,'RegDeleteKeyW',0x80000001,m.str('Software\\AsterTest',true)),0);});
await check('Registry keys, value types and byte budgets cannot be exceeded',async()=>{const r=await runtime(),m=r.mem,h=regkey(r);assert.equal(R(r,'RegSetValueExW',h,0,0,4,m.alloc(4),3),87);assert.equal(R(r,'RegSetValueExW',h,0,0,1,m.alloc(8),3),87);assert.equal(R(r,'RegSetValueExW',h,0,0,3,m.alloc(8),16385),87);for(let i=0;i<249;i++)regkey(r,'key'+i);const p=m.alloc(4);assert.equal(R(r,'RegCreateKeyExW',0x80000001,m.str('OverBudget',true),0,0,0,0x3f,0,p,0),8);});
await check('WM_DESTROY and WM_NCDESTROY observe correct child and HWND lifetimes',async()=>{const r=await runtime(),events=[],trace=[];r.host=e=>events.push(e);r.classes.set('probe',{proc:0x401000,extra:8,background:0});let parent,child;r.invoke=async(proc,[h,msg])=>{if(msg===0x81)return 1;if(msg===2||msg===0x82){trace.push([h,msg]);assert(r.handles.has(h));if(h===parent)assert.equal(r.handles.has(child),msg===2);}return 0;};parent=await r.gui.createWindow(true,0,'probe','Parent',0x10cf0000,0,0,300,200,0,0,r.image.base,0);child=await r.gui.createWindow(true,0,'probe','Child',0x50000000,0,0,30,20,parent,12,r.image.base,0);await r.destroyWindow(parent);assert.deepEqual(trace,[[parent,2],[child,2],[child,0x82],[parent,0x82]]);assert(!r.handles.has(parent));assert(!r.handles.has(child));});
await check('Failed WM_NCCREATE sends cleanup but not WM_CREATE or WM_DESTROY',async()=>{const r=await runtime(),calls=[];r.classes.set('failed',{proc:0x401000,extra:0});r.invoke=async(p,a)=>{calls.push(a[1]);return 0;};assert.equal(await r.gui.createWindow(true,0,'failed','Failed',0,0,0,100,100,0,0,r.image.base,0),0);assert.deepEqual(calls,[0x81,0x82]);assert.equal(r.gui.win(r.mainWindow),null);});
await check('Window userdata, extra DWORDs and parent cycles are bounded',async()=>{const r=await runtime();r.classes.set('extra',{proc:0,extra:8});const h=await r.gui.createWindow(true,0,'extra','Title',0,0,0,100,100,0,0,r.image.base,0);assert.equal(U(r,'SetWindowLongW',h,-21,42),0);assert.equal(U(r,'GetWindowLongW',h,-21),42);U(r,'SetWindowLongW',h,4,77);assert.equal(U(r,'GetWindowLongW',h,4),77);assert.equal(U(r,'SetWindowLongW',h,8,99),0);assert.equal(r.lastError,1413);assert.equal(U(r,'SetWindowLongW',h,-8,h),0);assert.equal(r.lastError,87);await r.destroyWindow(h);});
await check('Menu mutations keep IDs, checks, disabled state and reject cycles',async()=>{const r=await runtime(),m=r.mem,menu=U(r,'CreateMenu'),sub=U(r,'CreatePopupMenu');assert.equal(U(r,'AppendMenuW',sub,0,15,m.str('Item',true)),1);assert.equal(U(r,'AppendMenuW',menu,0x10,sub,m.str('Sub',true)),1);assert.equal(U(r,'CheckMenuItem',menu,15,8),0);assert.equal(U(r,'EnableMenuItem',menu,15,1),0);assert.equal(U(r,'GetMenuState',menu,15,0)&9,9);assert.equal(U(r,'AppendMenuW',sub,0x10,menu,m.str('Cycle',true)),0);assert.equal(r.lastError,87);assert.equal(U(r,'GetMenuItemCount',sub),1);assert.equal(U(r,'DestroyMenu',menu),1);assert.equal(U(r,'IsMenu',sub),0);});
await check('Private MessageBox disables only its owner and restores it after response',async()=>{let r;r=await runtime(e=>{if(e.type==='messagebox'){assert.equal(U(r,'IsWindowEnabled',e.hwnd),0);setTimeout(()=>r.event({type:'response',id:e.id,value:7}),1);}});const h=await r.gui.createWindow(true,0,'STATIC','Owner',0x10000000,0,0,100,100,0,0,r.image.base,0),m=r.mem;assert.equal(await U(r,'MessageBoxW',h,m.str('Question',true),m.str('Title',true),4),7);assert.equal(U(r,'IsWindowEnabled',h),1);await r.destroyWindow(h);});
await check('EDIT selection, replacement and numeric dialog values use guest UTF-16',async()=>{const r=await runtime(),m=r.mem,h=await r.gui.createWindow(true,0,'STATIC','Parent',0x10000000,0,0,100,100,0,0,r.image.base,0),child=await r.gui.createWindow(true,0,'EDIT','123',0x50000000,0,0,30,20,h,5,r.image.base,0);const out=m.alloc(4);assert.equal(U(r,'GetDlgItemInt',h,5,out,0),123);assert.equal(m.u32(out),1);await U(r,'SendMessageW',child,0xb1,0,-1);await U(r,'SendMessageW',child,0xc2,0,m.str('Zażółć',true));assert.equal(r.gui.win(child).text,'Zażółć');assert.equal(U(r,'GetDlgItemInt',h,5,out,0),0);assert.equal(m.u32(out),0);assert.equal(U(r,'SetDlgItemInt',h,5,0xffffffff,1),1);assert.equal(r.gui.win(child).text,'-1');await r.destroyWindow(h);});
await check('Rectangles and virtual client/screen transforms round-trip',async()=>{const r=await runtime(),m=r.mem,p=m.alloc(16);U(r,'SetRect',p,1,2,10,20);assert.equal(U(r,'PtInRect',p,9,19),1);assert.equal(U(r,'PtInRect',p,10,20),0);U(r,'AdjustWindowRect',p,0x00cf0000,1);const rect=r.gui.rect(p);assert.deepEqual(rect,[-3,-48,14,24]);const h=await r.gui.createWindow(true,0,'STATIC','Test',0x10cf0000,10,20,100,100,0,0,r.image.base,0);m.w32(p,7);m.w32(p+4,9);U(r,'ClientToScreen',h,p);U(r,'ScreenToClient',h,p);assert.deepEqual([m.i32(p),m.i32(p+4)],[7,9]);await r.destroyWindow(h);});
await check('Original WineMine bitmap decoding agrees with independent Pillow hashes',async()=>{const r=await runtime(),gold=JSON.parse(fs.readFileSync(root+'/tests/win32/fixtures/winemine-pixels.json'));for(const item of gold){const b=U(r,'LoadBitmapW',0,item.id),o=r.bitmapObject(b);assert.deepEqual([o.width,o.height],[item.width,item.height]);assert.equal(crypto.createHash('sha256').update(o.pixels).digest('hex'),item.rgbaSha256);G(r,'DeleteObject',b);}});
await check('24-bit bottom-up DIBs decode padded rows; encoding is reversible',async()=>{const r=await runtime(),m=r.mem,p=header(r,1,2,24),info=W.dibInfo(m,p),raw=Uint8Array.from([0,0,255,0,255,0,0,0]),pixels=W.decodePixels(raw,info);assert.deepEqual([...pixels],[0,0,255,255,255,0,0,255]);assert.deepEqual([...W.encodePixels(pixels,info)],[...raw]);});
await check('16-bit bitfield DIBs honor 565 masks and reject overlapping channels',async()=>{const r=await runtime(),m=r.mem,p=header(r,1,-1,16);m.w32(p+16,3);m.w32(p+40,0xf800);m.w32(p+44,0x7e0);m.w32(p+48,0x1f);const info=W.dibInfo(m,p);assert.deepEqual([...W.decodePixels(Uint8Array.from([0,248,0,0]),info)],[255,0,0,255]);m.w32(p+48,0x7e0);assert.throws(()=>W.dibInfo(m,p),/masks/);});
await check('1-bit palettes and top-down DIBs retain MSB-first bit order',async()=>{const r=await runtime(),m=r.mem,p=header(r,2,-1,1);m.w32(p+40,0);m.w32(p+44,0xffffff);const info=W.dibInfo(m,p);assert.deepEqual([...W.decodePixels(Uint8Array.from([0x80,0,0,0]),info)],[255,255,255,255,0,0,0,255]);assert.throws(()=>W.decodePixels(new Uint8Array(3),info),/Truncated/);});
await check('DIB dimensions, palette and compressed formats fail without allocating pixels',async()=>{const r=await runtime(),m=r.mem;assert.throws(()=>W.dibInfo(m,header(r,2049,2)),/dimensions/);const p=header(r,4,4,8);m.w32(p+32,257);assert.throws(()=>W.dibInfo(m,p),/palette/);m.w32(p+32,0);m.w32(p+16,1);assert.throws(()=>W.dibInfo(m,p),/Compressed/);assert.equal(r.bitmaps.pixels,0);});
await check('Bitmap selection excludes simultaneous DC ownership and deletion while selected',async()=>{const r=await runtime(),a=G(r,'CreateCompatibleDC',0),b=G(r,'CreateCompatibleDC',0),bitmap=G(r,'CreateCompatibleBitmap',a,4,4),old=G(r,'SelectObject',a,bitmap);assert(old);assert.equal(G(r,'SelectObject',b,bitmap),0);assert.equal(G(r,'DeleteObject',bitmap),0);G(r,'SelectObject',a,old);assert.equal(G(r,'DeleteObject',bitmap),1);G(r,'DeleteDC',a);G(r,'DeleteDC',b);assert.equal(r.bitmaps.pixels,1);});
await check('Actual x86 stores dirty watched pages, including cross-page writes',async()=>{const r=await runtime(),m=r.mem,c=r.cpu,ptr=0x900ffe,code=0x600000;assert.equal(c.page_version(ptr>>>12),0);c.watch_memory(ptr,4,1);const before=[c.page_version(ptr>>>12),c.page_version((ptr+3)>>>12)];m.copy(code,Uint8Array.from([0xc7,0x05,...u32(ptr),...u32(0x12345678),0xc3]));c.mark_executable(code,32);await r.invoke(code,[]);assert.equal(m.u32(ptr),0x12345678);assert(c.page_version(ptr>>>12)>before[0]);assert(c.page_version((ptr+3)>>>12)>before[1]);assert.equal(c.page_version(0x920000>>>12),0);m.w32(0x920000,42);assert.equal(c.page_version(0x920000>>>12),0);});
await check('Watch reference counts handle multiple DIBs sharing a page',async()=>{const r=await runtime(),c=r.cpu,p=0x900000;c.watch_memory(p,4,1);c.watch_memory(p+4,4,1);c.watch_memory(p,4,0);const a=c.page_version(p>>>12);r.mem.w32(p+4,42);assert(c.page_version(p>>>12)>a);c.watch_memory(p+4,4,0);const b=c.page_version(p>>>12);r.mem.w32(p,43);assert.equal(c.page_version(p>>>12),b);});
await check('DIBSection observes real guest CPU writes and GetObject returns its pointer',async()=>{const r=await runtime(),m=r.mem,p=header(r,1,-1),out=m.alloc(4),dc=G(r,'CreateCompatibleDC',0),b=G(r,'CreateDIBSection',dc,p,0,out,0,0),ptr=m.u32(out),info=m.alloc(84);G(r,'SelectObject',dc,b);assert.equal(G(r,'GetObjectW',b,84,info),84);assert.equal(m.u32(info+20),ptr);const code=0x600000;m.copy(code,Uint8Array.from([0xc7,0x05,...u32(ptr),...u32(0x00123456),0xc3]));r.cpu.mark_executable(code,32);await r.invoke(code,[]);assert.equal(G(r,'GetPixel',dc,0,0),0x563412);assert.equal(r.bitmaps.dibRefreshes,1);G(r,'GetPixel',dc,0,0);assert.equal(r.bitmaps.dibRefreshes,1);});
await check('Static sprite blits upload once and retain ordering across bitmap deletion',async()=>{const events=[],r=await runtime(e=>events.push(e)),h=await r.gui.createWindow(true,0,'STATIC','Bitmap',0x10000000,0,0,40,40,0,0,r.image.base,0),dc=r.dc(h),src=G(r,'CreateCompatibleDC',dc),b=U(r,'LoadBitmapW',0,4),old=G(r,'SelectObject',src,b);for(let i=0;i<30;i++)G(r,'BitBlt',dc,0,0,16,16,src,0,144,0xcc0020);G(r,'SelectObject',src,old);G(r,'DeleteObject',b);await r.flush();assert.equal(r.bitmaps.uploads,1);assert.equal(r.bitmaps.cacheHits,29);const commands=events.filter(e=>e.type==='draw').flatMap(e=>e.commands);assert.equal(commands[0].op,'bitmap');assert.equal(commands.filter(c=>c.op==='blit').length,30);assert.equal(commands.at(-1).op,'deletebitmap');await r.destroyWindow(h);});
await check('Overlapping memory BitBlt uses source snapshot and writes guest DIB bytes',async()=>{const r=await runtime(),m=r.mem,p=header(r,3,-1),out=m.alloc(4),dc=G(r,'CreateCompatibleDC',0),b=G(r,'CreateDIBSection',dc,p,0,out,0,0),ptr=m.u32(out);G(r,'SelectObject',dc,b);m.copy(ptr,Uint8Array.from([0,0,255,0,0,255,0,0,255,0,0,0]));assert.equal(G(r,'BitBlt',dc,1,0,2,1,dc,0,0,0xcc0020),1);assert.equal(G(r,'GetPixel',dc,1,0),255);assert.equal(G(r,'GetPixel',dc,2,0),0xff00);assert.deepEqual([...m.bytes.slice(ptr+4,ptr+7)],[0,0,255]);assert.throws(()=>G(r,'BitBlt',dc,0,0,1,1,dc,0,0,0x660046),/SRCCOPY/);});
await check('Memory DC vector drawing updates pixels without emitting desktop commands',async()=>{const events=[],r=await runtime(e=>events.push(e)),dc=G(r,'CreateCompatibleDC',0),bitmap=G(r,'CreateCompatibleBitmap',dc,3,3);G(r,'SelectObject',dc,bitmap);const p=r.mem.alloc(16);U(r,'SetRect',p,0,0,2,2);const brush=G(r,'CreateSolidBrush',0x332211);U(r,'FillRect',dc,p,brush);assert.equal(G(r,'GetPixel',dc,1,1),0x332211);assert.equal(G(r,'GetPixel',dc,2,2),0);assert(!events.some(e=>e.type==='draw'));});
await check('WineMine machine code processes a modal Custom dialog and saves private registry',async()=>{let r;const events=[];r=await runtime(e=>{events.push(e);if(e.type==='window'&&e.dialog&&e.title==='Custom Game'){setTimeout(()=>{const h=e.hwnd,rows=r.gui.children(h).find(([,w])=>w.id===1032)?.[0],cols=r.gui.children(h).find(([,w])=>w.id===1031)?.[0],mines=r.gui.children(h).find(([,w])=>w.id===1033)?.[0],ok=r.gui.children(h).find(([,w])=>w.id===1)?.[0];if(!ok)return;r.event({type:'text',hwnd:rows,text:'12'});r.event({type:'text',hwnd:cols,text:'13'});r.event({type:'text',hwnd:mines,text:'20'});r.event({type:'button',hwnd:ok});},25);}});
 const task=r.run();try{await wait(()=>r.gui.win(r.mainWindow)?.width===154&&events.some(e=>e.type==='idle'));r.event({type:'menu',hwnd:r.mainWindow,id:1008});await wait(()=>r.gui.win(r.mainWindow)?.width===218);assert.equal(r.gui.win(r.mainWindow).height,230);r.event({type:'menu',hwnd:r.mainWindow,id:1002});await task;assert.equal(r.exitCode,0);const saved=r.exportRegistry(),key=saved.keys.find(k=>k.path==='hkcu\\software\\microsoft\\winmine');assert.equal(new DataView(key.values.find(v=>v.name==='Width').bytes.buffer).getUint32(0,true),13);assert(r.apiCounts['user32.dll!DialogBoxParamW']>=1);return{instructions:r.cpu.instruction_count(),bitmaps:r.bitmaps,registryValues:key.values.length};}finally{r.exit(125);await task;}
});
const out=root+'/tests/win32/artifacts/gui';fs.mkdirSync(out,{recursive:true});fs.writeFileSync(out+'/unit-results.json',JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.tests.filter(t=>t.status==='PASS').length,failed:report.tests.filter(t=>t.status==='FAIL').length},null,2));
})().catch(e=>{console.error(e);process.exitCode=1;});
