'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const M=require('../../src/desktop-models.js'),ZIP=require('../../src/archives.js');
test('clipboard is bounded, deduplicated, pin-preserving and rejects oversized entries',()=>{const c=new M.ClipboardHistory();const first=c.add('pin');c.pin(first.id);for(let i=0;i<40;i++)c.add('note-'+i);assert.equal(c.entries.length,25);assert(c.entries.some(e=>e.text==='pin'));c.add('note-39');assert.equal(c.entries.length,25);assert.equal(c.add('x'.repeat(16385)),false);c.clear();assert.equal(c.entries.length,1);assert.equal(new M.ClipboardHistory(c.saved()).entries[0].pinned,true);c.clear(true);assert.equal(c.entries.length,0);});
test('full pinned history cannot silently lose pinned snippets',()=>{const c=new M.ClipboardHistory();for(let i=0;i<25;i++)c.add('pin'+i,true);assert.equal(c.add('26'),false);assert.equal(c.entries.length,25);});
test('focus deadlines survive pause, resume and reload; completion is exactly once',()=>{let f=new M.FocusSession({},1000);f.start(1,'Test',1000);f.pause(31000);assert.equal(f.remaining(50000),30000);f.resume(51000);f=new M.FocusSession(f.state,70000);assert.equal(f.remaining(70000),11000);assert(!f.tick(80000));assert(f.tick(81000));assert(!f.tick(82000));assert.equal(f.state.completed.length,1);assert.equal(f.today(81000),1);f.cancel();assert.equal(f.state.status,'idle');assert.throws(()=>f.start(500));});
test('quiet hours handle overnight boundaries without suppressing all day for equal endpoints',()=>{const s={enabled:true,start:'22:00',end:'08:00'},d=(h,m)=>new Date(2026,8,8,h,m);assert(M.inQuietHours(s,d(23,0)));assert(M.inQuietHours(s,d(7,59)));assert(!M.inQuietHours(s,d(8,0)));assert(!M.inQuietHours(s,d(21,59)));assert(!M.inQuietHours({...s,end:'22:00'},d(22,1)));assert(!M.inQuietHours({...s,start:'99:00'},d(10,0)));});
test('file history pruning honors per-file, total-count and byte budgets',()=>{let rows=[];for(let i=0;i<12;i++)rows=M.pruneHistory(rows,{id:i,path:'a',size:1}).rows;assert.equal(rows.length,10);assert.equal(rows[0].id,2);const p=M.pruneHistory(rows,{id:13,path:'b',size:20},{maxCount:10,maxBytes:25,perFile:10});assert.equal(p.rows.reduce((n,e)=>n+e.size,0),25);assert(p.removed.length>0);});
test('saved window state omits document bodies, tokens and arbitrary objects',()=>{const safe=M.safeWindowState({path:'/Documents/a.txt',text:'secret',token:'credential',section:'about',data:{}});assert.deepEqual(safe,{path:'/Documents/a.txt',section:'about'});});
test('layout groups stay in viewport and do not overlap',()=>{for(const layout of ['columns','grid','primary'])for(let n=1;n<=4;n++){const rects=M.layoutRects(layout,n,{w:1440,h:910});assert.equal(rects.length,n);for(const r of rects)assert(r.x>=0&&r.y>=0&&r.x+r.w<=1440&&r.y+r.h<=910);for(let i=0;i<n;i++)for(let j=i+1;j<n;j++){const a=rects[i],b=rects[j];assert(a.x+a.w<=b.x||b.x+b.w<=a.x||a.y+a.h<=b.y||b.y+b.h<=a.y);}}});
test('ZIP stored/deflate round trip retains Unicode names, empty folders and binary bytes',async()=>{for(const compress of [false,true]){const entries=[{name:'Folder/',bytes:new Uint8Array()},{name:'Folder/Zażółć.txt',bytes:new TextEncoder().encode('Unicode words '.repeat(1000))},{name:'binary.bin',bytes:Uint8Array.from({length:256},(_,i)=>i)}];const blob=await ZIP.pack(entries,compress);const bytes=new Uint8Array(await blob.arrayBuffer());assert.equal(ZIP.inspect(bytes).entries.length,3);const out=await ZIP.unpack(bytes);for(let i=0;i<3;i++){assert.equal(out[i].name,entries[i].name);assert.deepEqual(out[i].bytes,entries[i].bytes);}}});
test('ZIP path traversal, absolute, hidden and device paths are rejected',()=>{for(const path of ['../secret','/abs','C:/abs','a\\b','a/../b','a//b','.hidden','a/.b','a\0b','a./b'])assert.throws(()=>ZIP.safeName(path));});
test('ZIP CRC32 matches independent standard vector',()=>assert.equal(ZIP.crc32(new TextEncoder().encode('123456789')),0xcbf43926));
test('ZIP corrupt content, mismatched headers, duplicates and truncation fail',async()=>{const data=new Uint8Array(await(await ZIP.pack([{name:'a.txt',bytes:new Uint8Array([1,2,3])}],false)).arrayBuffer());const corrupt=data.slice();corrupt[35]^=1;await assert.rejects(()=>ZIP.unpack(corrupt));assert.throws(()=>ZIP.inspect(data.slice(0,-1)));await assert.rejects(()=>ZIP.pack([{name:'a',bytes:[]},{name:'A',bytes:[]}]));const mismatch=data.slice();new DataView(mismatch.buffer).setUint32(18,2,true);assert.throws(()=>ZIP.inspect(mismatch));});
test('ZIP expanded-size bomb is refused before decompression',async()=>{const data=new Uint8Array(await(await ZIP.pack([{name:'a',bytes:new Uint8Array([1])}],false)).arrayBuffer()),v=new DataView(data.buffer),central=32;v.setUint32(central+24,ZIP.LIMIT+1,true);assert.throws(()=>ZIP.inspect(data),/size/i);});

test('clipboard pinned ordering survives serialization without reversing',()=>{const c=new M.ClipboardHistory();c.add('first',true);c.add('second',true);assert.deepEqual(new M.ClipboardHistory(c.saved()).saved(),c.saved());});
test('ZIP symlink, encrypted entry and unsupported compression reject before allocation',async()=>{const bytes=new Uint8Array(await(await ZIP.pack([{name:'safe.txt',bytes:new Uint8Array([0])}],false)).arrayBuffer()),v=new DataView(bytes.buffer),central=v.getUint32(bytes.length-6,true);for(const change of [(v)=>v.setUint32(central+38,0xa000<<16,true),(v)=>v.setUint16(central+8,0x801,true),(v)=>v.setUint16(central+10,99,true)]){const b=bytes.slice();change(new DataView(b.buffer));assert.throws(()=>ZIP.inspect(b));}});
test('ZIP extraction rejects a conflicting file parent',async()=>{const b=await ZIP.pack([{name:'a',bytes:[]},{name:'a/b',bytes:[]}]);const bytes=new Uint8Array(await b.arrayBuffer());assert.throws(()=>ZIP.inspect(bytes));});
