'use strict';
const M=require('../../src/theme-models.js');
function cursor(red=220,green=80,blue=60){
 const n=16, stride=4, b=Buffer.alloc(22+40+n*n*4+stride*n);b.writeUInt16LE(2,2);b.writeUInt16LE(1,4);b[6]=b[7]=n;b.writeUInt16LE(1,10);b.writeUInt16LE(1,12);b.writeUInt32LE(b.length-22,14);b.writeUInt32LE(22,18);b.writeUInt32LE(40,22);b.writeInt32LE(n,26);b.writeInt32LE(n*2,30);b.writeUInt16LE(1,34);b.writeUInt16LE(32,36);b.writeUInt32LE(n*n*4,42);
 for(let at=62;at<62+n*n*4;at+=4){b[at]=blue;b[at+1]=green;b[at+2]=red;b[at+3]=255;}return b;
}
function chunk(id,data){const b=Buffer.alloc(8+data.length+(data.length%2));b.write(id,0,4,'ascii');b.writeUInt32LE(data.length,4);data.copy(b,8);return b;}
function ani(){const h=Buffer.alloc(36);[36,2,2,16,16,32,1,6,1].forEach((v,i)=>h.writeUInt32LE(v,i*4));const body=Buffer.concat([Buffer.from('ACON'),chunk('anih',h),chunk('LIST',Buffer.concat([Buffer.from('fram'),chunk('icon',cursor()),chunk('icon',cursor(40,100,230))]))]);return chunk('RIFF',body);}
function wave(){const n=800,b=Buffer.alloc(44+n*2);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(8000,24);b.writeUInt32LE(16000,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(n*2,40);for(let i=0;i<n;i++)b.writeInt16LE(Math.round(2000*Math.sin(i/8000*660*Math.PI*2)),44+i*2);return b;}
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAACAAAAAYCAIAAAAUMWhjAAAAJklEQVR4nGPUqLjEQEvARFPTRy0YtWDUglELRi0YtWDUglELqAYABUwBoiLp09gAAAAASUVORK5CYII=','base64');
function theme(){const assets={};for(const [name,mime,data] of [['background.png','image/png',png],['pointer.cur','image/x-icon',cursor()],['wait.ani','application/x-navi-animation',ani()],['notify.wav','audio/wav',wave()]])assets[name]={mime,data:data.toString('base64')};return M.normalize({title:'Independent test theme',profile:'macos26',accent:'#ac2589',background:{type:'picture',images:['background.png']},cursor:{custom:{Arrow:'pointer.cur',Wait:'wait.ani'}},sounds:{enabled:true,scheme:'custom',events:{SystemAsterisk:'notify.wav'}},assets});}
module.exports={cursor,ani,wave,png,theme};
if(require.main===module){const fs=require('node:fs'),path=require('node:path'),P=require('../../src/theme-packs.js'),out=process.argv[2];fs.mkdirSync(out,{recursive:true});const t=theme();fs.writeFileSync(path.join(out,'test.astertheme'),JSON.stringify({format:'aster-theme',version:1,theme:t}));fs.writeFileSync(path.join(out,'test.theme'),M.toWindows(t));for(const[n,a]of Object.entries(t.assets))fs.writeFileSync(path.join(out,n),Buffer.from(a.data,'base64'));fs.writeFileSync(path.join(out,'test.themepack'),P.pack([{name:'test.theme',bytes:Buffer.from(M.toWindows(t))},...Object.entries(t.assets).map(([name,a])=>({name,bytes:Buffer.from(a.data,'base64')}))]));fs.writeFileSync(path.join(out,'large.bin'),Buffer.from(Array.from({length:100000},(_,i)=>(i*17+(i>>>6))&255)));}
