'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {root,Runtime,wasm,u32}=require('../win32/runner.cjs');
const W=globalThis.AsterWin32;let compiled;
async function runtime(host=()=>{}){compiled||=await WebAssembly.compile(wasm);const r=await Runtime.create(compiled,host);r.load(fs.readFileSync(root+'/src/win32/examples/pad.exe'),'pad.exe');return r;}
const api=(r,n,...a)=>r.apis.get('user32.dll!'+n).fn(...a);
async function window(r){return r.gui.createWindow(true,0,'STATIC','Theme test',0x10000000,0,0,80,80,0,0,r.image.base,0);}
test('System colors are process-local and GetSysColor sees validated snapshots',async()=>{const a=await runtime(),b=await runtime();const old=api(b,'GetSysColor',5),p=a.systemColors.slice();p[5]=0x332211;assert.equal(a.setSystemColors(p,false),true);assert.equal(api(a,'GetSysColor',5),0x332211);assert.equal(api(b,'GetSysColor',5),old);assert.equal(api(a,'GetSysColor',99),0);});
test('Cached stock color brushes retain handles and reflect new palette values',async()=>{const r=await runtime(),h=api(r,'GetSysColorBrush',5),p=r.systemColors.slice();assert.equal(api(r,'GetSysColorBrush',5),h);p[5]=0x563412;r.setSystemColors(p,false);assert.equal(api(r,'GetSysColorBrush',5),h);assert.deepEqual(r.handles.get(h).color,W.color(p[5]));assert.equal(api(r,'GetSysColorBrush',-1),0);assert.equal(r.apis.get('gdi32.dll!DeleteObject').fn(h),0);});
test('Theme events enqueue ordinary Win32 color/theme/paint notifications without executing callbacks',async()=>{const r=await runtime(),h=await window(r);r.messages=[];const p=r.systemColors.slice();p[5]^=0xffffff;r.event({type:'theme',colors:p});assert.deepEqual(r.messages.filter(m=>m.hwnd===h).map(m=>m.message),[0x15,0x31a,15]);assert(r.gui.win(h).erase);});
test('Repeated updates coalesce pending theme notifications and preserve unrelated guest messages',async()=>{const r=await runtime(),h=await window(r);r.messages=[{hwnd:h,message:273,wParam:7,lParam:0}];for(let i=0;i<100;i++){const p=r.systemColors.slice();p[5]=i;r.setSystemColors(p);}assert.equal(r.messages.length,4);assert.equal(r.messages[0].message,273);assert.equal(api(r,'GetSysColor',5),99);});
test('Invalid palettes and saturated queues do not partially update colors or brushes',async()=>{const r=await runtime();await window(r);const old=r.systemColors.slice();assert.throws(()=>r.setSystemColors([1]));const malformed=old.slice();malformed[4]=-1;assert.throws(()=>r.setSystemColors(malformed));assert.deepEqual(r.systemColors,old);r.messages=Array.from({length:1024},()=>({hwnd:1,message:273}));const p=old.slice();p[5]^=0xffffff;assert.equal(r.setSystemColors(p),false);assert.deepEqual(r.systemColors,old);assert.equal(r.messages.length,1024);});
test('Real x86 import calls observe the new system color through the API thunk',async()=>{const r=await runtime(),p=r.systemColors.slice();p[5]=0x123456;r.setSystemColors(p,false);const entry=r.apis.get('user32.dll!GetSysColor');assert(entry);const code=0x600000;r.mem.copy(code,Uint8Array.from([0x6a,5,0xb8,...u32(entry.address),0xff,0xd0,0xc3]));r.cpu.mark_executable(code,32);assert.equal(await r.invoke(code,[]),0x123456);});
