/* Orbit Browser: honest external navigation, persistent library and embedded views. MIT. */
'use strict';
(() => {
    const OS=Aster,M=AsterOrbitModels,N=AsterWebNavigation,S=OS.orbit,el=OS.el;
    const button=(icon,label,fn)=>el('button',{type:'button',class:'icon-button',title:label,'aria-label':label,html:OS.icon(icon,18),onclick:OS.guard(fn)});
    const action=(label,fn)=>el('button',{type:'button',class:'secondary',text:label,onclick:OS.guard(fn)});
    const internal=new Set(['aster://home','aster://apps','aster://bookmarks','aster://history','aster://settings']);
    OS.renderOrbitSettings=(container)=>{
        const fields=[],root=el('section',{class:'orbit-settings'}),row=(title,description,control)=>el('label',{class:'orbit-setting'},el('span',{},el('strong',{text:title}),el('small',{text:description})),control);
        const engine=el('select',{'aria-label':'Search engine'});for(const [value,label] of [['duckduckgo','DuckDuckGo'],['google','Google'],['bing','Bing']])engine.append(el('option',{value,text:label}));
        root.append(row('Search engine','Searches open in a real browser tab by default. No proxy or remote page rewriting is used.',engine));fields.push(['engine',engine]);
        engine.onchange=OS.guard(()=>S.preferences({engine:engine.value}));
        for(const [key,label,description] of [
            ['recordHistory','Remember browsing history','Off by default. Stores up to 200 addresses requested in Orbit, including URL query strings; it cannot track other browser tabs.'],
            ['restoreTabs','Restore Orbit addresses with desktop sessions','Off by default. Restored remote addresses wait for your click before loading. Does not restore live pages, credentials, grants or browser-window sessions.'],
            ['confirmLeave','Confirm before unloading embedded pages','Protect unknown unsaved documents when closing, reloading or navigating. Cooperating pages can explicitly report whether they are dirty.']
        ]){const control=el('input',{type:'checkbox','aria-label':label});control.onchange=OS.guard(()=>S.preferences({[key]:control.checked}));fields.push([key,control]);root.append(row(label,description,control));}
        root.append(el('p',{class:'orbit-help',text:'Automatic mode opens ordinary websites in your real browser. Choose Embedded webview explicitly for sites that allow it. Site preferences change opening location only—not sandbox permissions.'}));
        const routes=el('div',{class:'orbit-site-routes'});root.append(el('h3',{text:'Saved site-opening preferences'}),routes);
        const render=()=>{if(!root.isConnected)return;const d=S.data;for(const [key,node]of fields){if(node.type==='checkbox')node.checked=d.preferences[key];else node.value=d.preferences[key];}routes.replaceChildren();for(const r of d.routes)routes.append(el('div',{class:'orbit-list-row'},el('code',{text:r.origin}),el('span',{text:r.mode==='webview'?'Webview':'Browser tab'}),action('Reset',()=>S.siteRoute(r.origin,'auto'))));if(!d.routes.length)routes.append(el('p',{class:'muted',text:'No overrides. Use Remember for this site in Orbit’s menu.'}));};
        const cleanup=OS.on('orbit-data',render);container.append(root);render();return cleanup;
    };
    OS.register('browser',{title:'Orbit Browser',description:'Browse websites, manage bookmarks and embed compatible web apps.',category:'Essentials',width:1080,height:730,minWidth:320,minHeight:300,
        mount:async(w,options)=>{
            await S.initialize();if(w.closed)return;
            const restored=options.state&&Array.isArray(options.state.tabs),savedState=structuredClone(w.state);
            delete w.state.url;delete w.state.path;delete w.state.mode;
            w.state.webview=options.webview===true||w.state.webview===true;w.state.compact=options.compact===true||w.state.compact===true;
            const root=el('div',{class:'orbit-browser'}),tabbar=el('div',{class:'browser-tabs',role:'tablist','aria-label':'Orbit tabs'}),nav=el('div',{class:'browser-nav'}),context=el('div',{class:'orbit-contextbar'}),holder=el('div',{class:'browser-content orbit-panes'});
            const compact=el('div',{class:'orbit-compactbar'},action('Show navigation',()=>{w.state.compact=false;chrome();persist();}),el('span',{text:'Embedded app window'}));
            let tabs=[],active=null,alive=true,closedTabs=[];
            const current=()=>tabs.find(t=>t.id===active);
            const back=button('back','Back',()=>travel(-1)),forward=button('forward','Forward',()=>travel(1)),reload=button('refresh','Reload',()=>navigate(current().url,false,{replace:true})),stop=button('stop','Stop and unload',async()=>{await current()?.view?.stop();refresh();}),home=button('home','Home',()=>navigate('aster://home'));
            const address=el('input',{class:'browser-address','aria-label':'Address or search',placeholder:'Search or enter a website address',autocomplete:'off',spellcheck:false});
            const mode=el('select',{'aria-label':'Open pages in',class:'orbit-mode'});for(const [value,label] of [['auto','Automatic'],['browser','Browser tab'],['webview','Embedded webview']])mode.append(el('option',{value,text:label}));
            const bookmark=button('star','Bookmark this address',()=>editBookmark()),more=button('more','Browser menu',e=>menu(e));
            const stateLabel=el('span',{role:'status',class:'orbit-context-status'});
            context.append(stateLabel,action('Bookmarks',()=>navigate('aster://bookmarks')),action('History',()=>navigate('aster://history')));
            nav.append(back,forward,reload,stop,home,address,mode,bookmark,more);root.append(tabbar,nav,context,compact,holder);w.body.append(root);
            const externalURL=()=>{const t=current();return t?.view?.currentURL()||t?.url;};
            function chrome(){tabbar.hidden=w.state.webview;nav.hidden=context.hidden=w.state.compact;compact.hidden=!w.state.compact;root.classList.toggle('orbit-single-view',w.state.webview);}
            function persist(){if(!alive||!tabs.length)return;Object.assign(w.state,M.session(tabs,tabs.findIndex(t=>t.id===active),S.data.preferences.restoreTabs));OS.saveSession();}
            function refresh(){const t=current();if(!t)return;const s=t.view?.snapshot;address.value=t.addressDraft??(s?.reportedURL||t.url);address.title=s?.reportedURL?'Page-reported address, limited to the requested origin.':'Last address requested in Orbit (not a complete record of in-page navigation).';mode.value=t.mode;back.disabled=t.index<=0;forward.disabled=t.index>=t.history.length-1;stop.disabled=!s?.hasFrame;reload.disabled=internal.has(t.url);bookmark.disabled=!/^https?:/.test(externalURL());bookmark.setAttribute('aria-pressed',String(S.data.bookmarks.some(b=>b.url===externalURL())));
                stateLabel.textContent=s?.reportedURL?'Page-reported address · '+(s.route==='webview'?'Webview':'Browser'):s?.route==='browser'?'Real browser tab · Orbit retains the requested address':s?.hasFrame?'Embedded webview · '+(s.status==='cooperative'?'cooperating page':'visibility may be restricted'):'Local to Aster · '+OS.db.mode;
                if(t.tabLabel)t.tabLabel.textContent=t.title||'New tab';if(t.tabIcon){const icon=t.url.startsWith('aster:')?'spark':'globe';if(t.tabIcon.dataset.orbitIcon!==icon){t.tabIcon.innerHTML=OS.icon(icon,14);t.tabIcon.dataset.orbitIcon=icon;}}if(t.tabNode)t.tabNode.title=t.title+'\n'+t.url;const title=(t.title||'Orbit')+(w.state.webview?' — Webview':' — Orbit Browser');if(w.title!==title)w.setTitle(title);w.dirty=tabs.some(tab=>tab.view?.state.dirty===true);chrome();}
            function renderTabs(){tabbar.replaceChildren();for(const t of tabs){const selected=t.id===active,node=el('div',{class:'browser-tab'+(selected?' active':''),role:'tab',tabindex:selected?'0':'-1','aria-selected':String(selected),'aria-controls':t.id,title:(t.title||'New tab')+'\n'+t.url});
                const label=el('span',{text:t.title||'New tab'}),close=button('close','Close tab',()=>{});node.append(el('i',{html:OS.icon(t.url.startsWith('aster:')?'spark':'globe',14)}),label,close);t.tabNode=node;t.tabLabel=label;t.tabIcon=node.firstElementChild;
                node.onclick=()=>activate(t.id);close.onclick=e=>{e.stopPropagation();OS.guard(closeTab)(t);};node.onauxclick=e=>{if(e.button===1){e.preventDefault();OS.guard(closeTab)(t);}};
                node.onkeydown=e=>{if(e.target!==node)return;const i=tabs.indexOf(t),j=e.key==='Home'?0:e.key==='End'?tabs.length-1:e.key==='ArrowLeft'?(i-1+tabs.length)%tabs.length:e.key==='ArrowRight'?(i+1)%tabs.length:-1;if(j>=0){e.preventDefault();activate(tabs[j].id);tabs[j].tabNode.focus();}else if(e.key==='Enter'||e.key===' '){e.preventDefault();activate(t.id);}};
                node.oncontextmenu=e=>OS.context(e,[{text:'Duplicate address in new tab',icon:'copy',action:()=>addTab(t.url,{mode:t.mode})},{text:'Close tab',icon:'close',action:()=>closeTab(t)},{text:'Reopen closed tab',icon:'restore',disabled:!closedTabs.length,action:()=>reopen()}]);tabbar.append(node);}
                tabbar.append(button('plus','New tab',()=>addTab()));}
            function activate(id){const t=tabs.find(t=>t.id===id);if(!t)return;active=id;for(const item of tabs)item.pane.hidden=item.id!==id;renderTabs();refresh();persist();}
            function disposeTab(t){t.request++;t.offView?.();t.offView=null;t.view?.dispose();t.view=null;t.internalCleanup?.();t.internalCleanup=null;t.pane.remove();}
            async function closeTab(t){if(!tabs.includes(t))return;if(t.closing)return;t.closing=true;try{if(t.view&&!await t.view.canLeave('Close this tab?'))return;if(!alive||!tabs.includes(t))return;closedTabs.unshift({url:t.url,mode:t.mode,zoom:t.zoom});closedTabs=closedTabs.slice(0,M.LIMITS.closed);const i=tabs.indexOf(t);disposeTab(t);tabs=tabs.filter(x=>x!==t);if(!tabs.length){await addTab();return;}activate(active===t.id?tabs[Math.max(0,i-1)].id:active);}finally{t.closing=false;}}
            async function reopen(){if(!closedTabs.length)return;const last=closedTabs.shift();await addTab(last.url,{...last,restored:true});}
            async function addTab(url='aster://home',opts={}){url=N.address(url,false);if(!alive)return;if(tabs.length>=M.LIMITS.tabs)throw Error('Close a tab first (20 maximum).');if(tabs.length&&w.state.webview)w.state.webview=false;const t={id:'orbit-'+OS.uid(),url,title:'New tab',mode:opts.mode||'auto',zoom:M.zoom(opts.zoom),history:[url],index:0,request:0,pane:el('div',{class:'browser-content orbit-pane',role:'tabpanel'})};t.pane.id=t.id;tabs.push(t);holder.append(t.pane);activate(t.id);await renderContent(t,opts);return t;}
            async function navigate(input,newTab=false,opts={}){const url=M.address(input,S.data.preferences.engine);if(newTab)return addTab(url,opts);const t=current();if(!t||!alive)return false;const request=++t.request,draft=t.addressDraft;
                if(t.view&&!await t.view.canLeave(opts.replace?'Reload this page?':'Leave the embedded page?'))return false;if(!alive||!tabs.includes(t)||request!==t.request)return false;
                if(t.addressDraft===draft)delete t.addressDraft;
                if(!opts.replace){t.history=M.push(t.history,t.index,url);t.index=t.history.length-1;}t.url=url;if(opts.mode)t.mode=opts.mode;const result=await renderContent(t,opts);if(alive&&tabs.includes(t)&&request===t.request){if(active===t.id)refresh();persist();}return result;}
            async function travel(delta){const t=current(),i=t.index+delta;if(i<0||i>=t.history.length)return;const request=++t.request;if(t.view&&!await t.view.canLeave())return;if(!alive||request!==t.request)return;delete t.addressDraft;t.index=i;t.url=t.history[i];await renderContent(t);if(alive&&active===t.id)refresh();persist();}
            async function renderContent(t,opts={}){
                if(!alive||!tabs.includes(t))return;const version=t.request,target=t.url;const valid=()=>alive&&tabs.includes(t)&&version===t.request&&target===t.url;
                if(internal.has(target)){t.offView?.();t.offView=null;t.view?.dispose();t.view=null;t.internalCleanup?.();t.internalCleanup=null;t.pane.replaceChildren();renderInternal(t);if(active===t.id)refresh();return true;}
                t.internalCleanup?.();t.internalCleanup=null;
                if(!t.view){t.pane.replaceChildren();t.view=OS.webviews.create(t.pane,{owner:w});t.offView=t.view.on('change',s=>{t.title=s.title;t.zoom=s.zoom;t.mode=s.mode;if(s.url!==t.url){t.url=s.url;t.history=M.push(t.history,t.index,s.url);t.index=t.history.length-1;}if(active===t.id)refresh();});}
                await t.view.load(target,{mode:t.mode,external:opts.external===true,restored:opts.restored===true});
                if(!valid())return false;t.title=t.view.state.title;t.view.setZoom(t.zoom);if(active===t.id)refresh();persist();if(/^https?:/.test(target)&&!opts.restored&&S.data.preferences.recordHistory)await S.record(target,t.title);return true;
            }
            function listPage(t,kind){const page=el('div',{class:'orbit-library'}),heading=kind==='bookmarks'?'Bookmarks':'Browsing history';t.title=heading;
                const top=el('div',{class:'orbit-library-heading'},el('h1',{text:heading})),search=el('input',{type:'search',placeholder:'Filter '+heading.toLowerCase(),'aria-label':'Filter '+heading.toLowerCase()}),list=el('div',{class:'orbit-link-list'});page.append(top,search);
                if(kind==='bookmarks')top.append(action('Import bookmarks',()=>S.importBookmarks()),action('Export bookmarks',()=>S.exportBookmarks()));else top.append(action('Clear history',async()=>{if(await OS.confirm('Clear browsing history?','Deletes Orbit’s saved requested addresses, not bookmarks or another browser’s history.','Clear history',true))await S.clearHistory();}));
                const note=el('p',{class:'orbit-help'});page.append(note,list);t.pane.append(page);
                const render=()=>{const data=S.data;note.textContent=kind==='bookmarks'?'Bookmarks stay in this browser. Opening a link uses its site preference; exports contain full URLs.':(data.preferences.recordHistory?'History recording is on.':'History recording is off. Previous records stay until you clear them.')+' This list records Orbit requests, not all navigation inside external pages.';
                    const query=search.value.toLocaleLowerCase(),items=data[kind].filter(x=>(x.title+' '+x.url).toLocaleLowerCase().includes(query));list.replaceChildren();for(const item of items){const row=el('div',{class:'orbit-list-row'}),link=action(item.title||item.url,()=>navigate(item.url));link.className='orbit-list-link';link.append(el('small',{text:item.url}));row.append(link);
                        if(kind==='bookmarks')row.append(action('Edit',async()=>{const title=await OS.prompt('Bookmark title',item.title,'Save');if(title!==null)await S.bookmark(item.url,title);}),action('Remove',()=>S.removeBookmark(item.url)));
                        else row.append(el('time',{text:item.time?new Date(item.time).toLocaleString():'Not recorded'}));list.append(row);}if(!items.length)list.append(el('p',{class:'orbit-empty',text:'No '+kind+' to display.'}));};
                search.oninput=render;t.internalCleanup=OS.on('orbit-data',render);render();}
            function renderInternal(t){if(t.url==='aster://settings'){t.title='Orbit settings';const page=el('div',{class:'orbit-library'},el('h1',{text:'Orbit settings'}));t.pane.append(page);t.internalCleanup=OS.renderOrbitSettings(page);return;}
                if(t.url==='aster://bookmarks'||t.url==='aster://history'){listPage(t,t.url.slice('aster://'.length));return;}
                const apps=t.url==='aster://apps';t.title=apps?'Your web apps':'New tab';const page=el('div',{class:'browser-home orbit-home'});
                page.append(el('div',{class:'orbit-eyebrow',text:'ORBIT BROWSER'}),el('h1',{text:apps?'Your web, in one place.':'Where will you go next?'}),el('p',{text:apps?'Launch your catalog apps or manage your local library.':'Websites in your browser. Compatible apps inside Aster.'}));
                const form=el('form',{class:'browser-home-search'}),search=el('input',{'aria-label':'Search the web',placeholder:apps?'Search your web apps':'Search the web or enter a website address',autocomplete:'off'}),go=el('button',{type:'submit',class:'primary',text:apps?'Find':'Go'});form.append(search,go);page.append(form);
                const links=el('div',{class:apps?'orbit-app-grid':'browser-links'});page.append(links);t.pane.append(page);
                form.onsubmit=e=>{e.preventDefault();if(!apps)OS.guard(navigate)(search.value,false,{external:e.isTrusted});};
                if(apps){const render=()=>{const query=search.value.toLowerCase();links.replaceChildren();for(const a of OS.webCatalog?.apps||[])if((a.title+' '+a.description).toLowerCase().includes(query))links.append(el('button',{class:'orbit-app-link',html:OS.appIcon(a.id,32),onclick:OS.guard(()=>navigate(a.url))},el('span',{},el('strong',{text:a.title}),el('small',{text:a.description}))));};search.oninput=render;render();}
                else {for(const [id,label,url]of [['store','Your web apps','aster://apps'],['star','Bookmarks','aster://bookmarks'],['clock','History','aster://history'],['settings','Browser settings','aster://settings']])links.append(el('button',{class:'browser-link',onclick:OS.guard(()=>navigate(url)),html:OS.icon(id,28)},el('span',{text:label})));
                    page.append(action('Open App Center',()=>OS.openApp('store',{mode:'installed'})),el('p',{class:'orbit-help',text:'Automatic mode avoids broken frames by opening ordinary sites in a real tab. Select Embedded webview for sites that permit framing. No browsing history is recorded unless you enable it.'}));}
            }
            async function editBookmark(){const url=M.webURL(externalURL()),entry=S.data.bookmarks.find(b=>b.url===url),title=await OS.prompt(entry?'Edit bookmark title':'Bookmark this address',entry?.title||current().title,'Save');if(title!==null)await S.bookmark(url,title);}
            function menu(e){const t=current(),url=externalURL(),remote=/^https?:/.test(url),embedded=!!t.view?.frame;
                OS.context(e,[{text:'Open in browser tab',icon:'external',disabled:!remote,action:()=>t.view.external('tab')},{text:'Open browser window',icon:'external',disabled:!remote,action:()=>t.view.external('window')},{text:'Try embedded webview',icon:'globe',disabled:!remote,action:()=>navigate(url,false,{mode:'webview'})},
                    {text:'Remember browser tab for this site',icon:'external',disabled:!remote,action:()=>S.siteRoute(url,'browser')},{text:'Remember webview for this site',icon:'globe',disabled:!remote,action:()=>S.siteRoute(url,'webview')},{text:'Use automatic mode for this site',icon:'refresh',disabled:!remote,action:()=>S.siteRoute(url,'auto')},null,
                    {text:'Open address as app webview',icon:'max',disabled:!remote&&!t.url.startsWith('aster://file/'),action:()=>OS.openWebview(url)},
                    {text:'Install website as app',icon:'store',disabled:!url?.startsWith('https:'),action:()=>OS.installWebLink({url,title:t.title,description:'Saved from Orbit Browser'})},
                    {text:'Save website shortcut in Files',icon:'save',disabled:!remote,action:()=>S.saveShortcut(url,t.title)},
                    {text:'Copy address',icon:'copy',disabled:!remote,action:async()=>{try{await navigator.clipboard.writeText(url);OS.notify('Address copied',url);}catch{await OS.prompt('Copy this address',url,'Done');}}},null,
                    {text:'Zoom in',icon:'plus',disabled:!embedded||t.zoom>=2,action:()=>{t.zoom=t.view.setZoom(t.zoom+.1);persist();}},{text:'Zoom out',icon:'min',disabled:!embedded||t.zoom<=.5,action:()=>{t.zoom=t.view.setZoom(t.zoom-.1);persist();}},{text:'Reset zoom ('+Math.round(t.zoom*100)+'%)',icon:'refresh',disabled:!embedded,action:()=>{t.zoom=t.view.setZoom(1);persist();}},null,
                    {text:'Reopen closed tab',icon:'restore',disabled:!closedTabs.length,action:reopen},{text:w.state.compact?'Show navigation':'Hide navigation',icon:'list',action:()=>{w.state.compact=!w.state.compact;chrome();persist();}},{text:'Orbit settings',icon:'settings',action:()=>navigate('aster://settings')}]);}
            // Loading/status/bookmark events must not overwrite typed or pasted input.
            // Keep drafts per live tab; they are not included in saved sessions.
            address.oninput=()=>{const t=current();if(t)t.addressDraft=address.value;};
            address.onfocus=()=>address.select();address.onkeydown=e=>{if(OS.input?.blocked(e)||e.defaultPrevented)return;if(e.key==='Escape'){e.preventDefault();delete current().addressDraft;refresh();address.select();}else if(e.key==='Enter'){e.preventDefault();OS.guard(navigate)(address.value,false,{external:e.isTrusted});}};
            mode.onchange=OS.guard(async()=>{const t=current(),selected=mode.value;if(await navigate(t.url,false,{mode:selected,replace:true}))t.mode=selected;refresh();});
            w.onKey=e=>{const ctrl=e.ctrlKey||e.metaKey,k=e.key.toLowerCase();if(e.altKey&&!ctrl&&(e.key==='ArrowLeft'||e.key==='ArrowRight')){e.preventDefault();OS.guard(travel)(e.key==='ArrowLeft'?-1:1);return;}if(!ctrl||e.altKey)return;
                if(['l','t','w','d','h','r'].includes(k)){e.preventDefault();e.stopPropagation();}
                if(k==='l'){w.state.compact=false;chrome();address.focus();address.select();}else if(k==='t'){if(e.shiftKey)OS.guard(reopen)();else OS.guard(addTab)();}else if(k==='w')OS.guard(closeTab)(current());else if(k==='d'&&!bookmark.disabled)OS.guard(editBookmark)();else if(k==='h')OS.guard(navigate)('aster://history');else if(k==='r')OS.guard(navigate)(current().url,false,{replace:true});};
            w.beforeClose=async()=>{const risky=tabs.filter(t=>t.view?.frame&&(t.view.state.dirty===true||t.view.state.dirty===null&&S.data.preferences.confirmLeave));return !risky.length||await OS.confirm('Close Orbit Browser?',risky.length+' embedded page(s) may contain unsaved work. External browser tabs are independent and will stay open.','Close browser');};
            w.extraTitleMenu=()=>[{text:'Orbit settings',icon:'settings',action:()=>navigate('aster://settings')},{text:w.state.compact?'Show navigation':'Hide navigation',icon:'list',action:()=>{w.state.compact=!w.state.compact;chrome();persist();}}];
            w.addCleanup(()=>{alive=false;for(const t of tabs)disposeTab(t);tabs=[];closedTabs=[];});w.on('orbit-data',()=>{refresh();persist();});
            w.navigate=navigate;w.openTab=addTab;w.browser=Object.freeze({navigate,back:()=>travel(-1),forward:()=>travel(1),reload:()=>navigate(current().url,false,{replace:true}),newTab:addTab,reopenClosed:reopen,current:()=>current()?.view?.snapshot||{url:current()?.url}});w.getTabs=()=>tabs.map(t=>({id:t.id,url:t.url,title:t.title,mode:t.mode,zoom:t.zoom,active:t.id===active,state:t.view?.snapshot||null}));w.getWebview=()=>current()?.view||null;
            if(restored&&S.data.preferences.restoreTabs){const saved=M.session(savedState.tabs,savedState.active,true);for(const t of saved.tabs)await addTab(t.url,{...t,restored:true});activate(tabs[saved.active].id);}
            else if(restored){await addTab();}
            else if(options.path){const path=String(options.path);if(/\.(url|asterlink)$/i.test(path)){const file=await OS.fs.read(path);if(file.size>M.LIMITS.shortcut)throw Error('The website shortcut is too large.');const link=M.shortcut(await OS.fs.text(file));await addTab(link.url,{mode:'auto'});}else await addTab(N.address('aster://file'+encodeURI(path).replace(/#/g,'%23').replace(/\?/g,'%3F'),false),{mode:'webview'});}
            else await addTab(options.url?N.address(options.url,false):'aster://home',{mode:options.mode||'auto'});
            refresh();persist();
        }
    });
})();
