/* Desktop essentials: real local data, explicit permissions, no remote services. MIT. */
'use strict';
(() => {
    const OS=Aster, M=AsterDesktopModels, $=OS.$;
    const button=(label,fn,primary=false)=>OS.el('button',{class:primary?'primary':'secondary',text:label,onclick:OS.guard(fn)});
    const icon=(name,label,fn)=>OS.el('button',{class:'icon-button',title:label,'aria-label':label,html:OS.icon(name,17),onclick:OS.guard(fn)});
    const note=text=>OS.el('p',{class:'suite-note',text});
    const field=(label,input)=>OS.el('label',{class:'suite-field'},OS.el('span',{text:label}),input);
    const select=(label,options,value,change)=>{const input=OS.el('select',{'aria-label':label});for(const [v,t]of options)input.append(OS.el('option',{value:v,text:t,selected:String(v)===String(value)}));input.onchange=OS.guard(()=>change(input.value));return input;};
    const toggle=(label,on,fn)=>{const input=OS.el('input',{type:'checkbox',checked:on,'aria-label':label});input.onchange=OS.guard(()=>fn(input.checked));return OS.el('label',{class:'suite-toggle'},input,OS.el('span',{text:label}));};
    const page=(w,title,description)=>{const root=OS.el('div',{class:'suite-app'});root.append(OS.el('header',{class:'suite-heading'},OS.el('span',{class:'eyebrow',text:'ASTER'}),OS.el('h1',{text:title}),note(description)));w.body.append(root);return root;};
    const saveWidgets=async()=>{await OS.featureSave('widget-board',OS.widgetBoard);OS.featureChange('widgets');};
    OS.desktopUI={button,icon,note,field,select,toggle,page};
    OS.register('clipboard',{title:'Clipboard History',icon:'paste',color:'blue',category:'Utilities',description:'Opt-in text history, pinned snippets, and paste into Aster editors.',width:540,height:630,singleton:true,mount(w){
        const root=page(w,'Clipboard history','Text copied inside Aster only. Password fields are excluded. Unpinned items are cleared when this page reloads; pinned text is stored in this browser.'),controls=OS.el('div',{class:'suite-actions'}),search=OS.el('input',{placeholder:'Search clipboard','aria-label':'Search clipboard'}),list=OS.el('div',{class:'suite-list'});
        const enabled=toggle('Enable clipboard history',OS.settings.clipboardHistory,async on=>{await OS.setSetting('clipboardHistory',on);if(!on){OS.clipboardText.model.clear(true);await OS.clipboardText.save();}render();});
        controls.append(button('Read system clipboard',async()=>{if(!OS.settings.clipboardHistory)throw Error('Enable clipboard history first.');await OS.clipboardText.readSystem();}),button('Clear unpinned',async()=>{OS.clipboardText.model.clear();await OS.clipboardText.save();}),button('Delete all',async()=>{if(await OS.confirm('Delete clipboard history?','Pinned snippets will also be removed from this browser.','Delete all',true)){OS.clipboardText.model.clear(true);await OS.clipboardText.save();}}));
        root.append(enabled,controls,search,list);search.oninput=render;
        function render(){list.replaceChildren();if(!OS.settings.clipboardHistory){list.append(note('History is off. Enable it above to start capturing text. No system clipboard polling is performed.'));return;}
            const rows=OS.clipboardText.model.entries.filter(e=>e.text.toLowerCase().includes(search.value.toLowerCase()));
            if(!rows.length)list.append(note('Copy text in an Aster editor, or use Read system clipboard with browser permission. Up to 25 items, 16 Ki characters each.'));
            for(const entry of rows){const card=OS.el('article',{class:'suite-card clip-card','data-clip':entry.id}),text=OS.el('pre',{text:entry.text}),actions=OS.el('div',{class:'suite-actions'});
                actions.append(button('Paste',()=>OS.clipboardText.paste(entry.id),true),button('Copy',async()=>{if(!navigator.clipboard?.writeText)throw Error('System clipboard access is unavailable. Use Paste into an Aster editor.');await navigator.clipboard.writeText(entry.text);}),button(entry.pinned?'Unpin':'Pin',async()=>{OS.clipboardText.model.pin(entry.id);await OS.clipboardText.save();}),icon('trash','Delete snippet',async()=>{OS.clipboardText.model.remove(entry.id);await OS.clipboardText.save();}));
                card.append(text,actions);list.append(card);}}
        w.on('feature-change',e=>{if(e.name==='clipboard')render();});render();
    }});
    OS.register('focus',{title:'Focus Sessions',icon:'clock',color:'violet',category:'Productivity',description:'Focus timer with daily goals, task selection, and quiet notification hours.',width:750,height:690,singleton:true,async mount(w){
        const root=page(w,'Time for what matters','Focus silences ordinary Aster toasts without changing your manual Do not disturb setting. Priority completion notices can still appear. This does not silence the host OS or embedded web apps.'),hero=OS.el('section',{class:'suite-card focus-hero'}),clock=OS.el('div',{class:'focus-countdown','aria-label':'Focus time remaining'}),status=OS.el('div',{class:'suite-note'}),progress=OS.el('progress',{max:1,value:0,'aria-label':'Focus session progress'}),actions=OS.el('div',{class:'suite-actions'});
        const minutes=OS.el('input',{type:'number',min:1,max:180,value:Math.round(OS.focusSession.state.duration/60000),'aria-label':'Session minutes'}),tasks=await OS.db.get('tasks')||[],task=select('Focus task',[['','No task'],...tasks.filter(t=>!t.done).map(t=>[t.title,t.title])],OS.focusSession.state.task,()=>{});
        const start=button('Start focus',()=>OS.focusAction('start',Number(minutes.value),task.value),true),pause=button('Pause',()=>OS.focusAction(OS.focusSession.state.status==='paused'?'resume':'pause')),end=button('End session',()=>OS.focusAction('cancel'));
        actions.append(start,pause,end);hero.append(clock,status,progress,actions);root.append(hero,OS.el('div',{class:'suite-columns'},field('Duration (minutes)',minutes),field('Work on a task',task)));
        const goal=OS.el('input',{type:'number',min:5,max:480,value:OS.focusSession.state.goal,'aria-label':'Daily focus goal'}),daily=OS.el('div',{class:'suite-card'});goal.onchange=OS.guard(async()=>{OS.focusSession.state.goal=M.clamp(goal.value,5,480,60);goal.value=OS.focusSession.state.goal;await OS.featureSave('focus-session',OS.focusSession.state);tick();});root.append(field('Daily goal (minutes)',goal),daily);
        const q=OS.quiet.schedule,from=OS.el('input',{type:'time',value:q.start,'aria-label':'Quiet hours start'}),to=OS.el('input',{type:'time',value:q.end,'aria-label':'Quiet hours end'});
        const saveQuiet=async()=>{q.start=from.value;q.end=to.value;await OS.featureSave('quiet-hours',q);tick();};from.onchange=to.onchange=OS.guard(saveQuiet);
        root.append(OS.el('h2',{text:'Notifications & quiet hours'}),toggle('Manual Do not disturb',OS.settings.dnd,on=>OS.setSetting('dnd',on)),toggle('Scheduled quiet hours',q.enabled,async on=>{q.enabled=on;await saveQuiet();}),OS.el('div',{class:'suite-columns'},field('From',from),field('Until',to)),button('Open Notification Center',()=>OS.showNotifications()));
        function tick(){const s=OS.focusSession.state,left=Math.ceil(OS.focusSession.remaining()/1000);clock.textContent=`${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}`;status.textContent=s.status==='running'?'Focusing · '+(s.task||'One thing at a time'):s.status==='paused'?'Paused':s.status==='complete'?'Session complete. Take a break.':'Ready when you are';progress.value=1-OS.focusSession.remaining()/s.duration;start.disabled=['running','paused'].includes(s.status);minutes.disabled=task.disabled=start.disabled;pause.disabled=!start.disabled;pause.textContent=s.status==='paused'?'Resume':'Pause';end.disabled=!start.disabled;daily.textContent=`Today: ${Math.round(OS.focusSession.today())} / ${s.goal} minutes · Aster notifications ${OS.quiet.active()?'quiet':'on'}`;}
        w.on('focus-tick',tick);w.on('feature-change',e=>{if(e.name==='focus')tick();});tick();
    }});
    OS.register('widgets',{title:'Widget Board',icon:'grid',color:'teal',category:'Productivity',description:'Your agenda, tasks, quick note, clock, focus progress and storage in customizable cards.',width:940,height:730,singleton:true,mount(w){
        const root=page(w,'Your day, at a glance','Live cards use your actual Aster tasks, calendar, files and focus sessions. No weather feed, account or tracking service.'),customize=OS.el('details',{class:'suite-card'}),options=OS.el('div',{class:'suite-actions'}),grid=OS.el('div',{class:'widget-board'});
        customize.append(OS.el('summary',{text:'Customize widgets'}),options);root.append(customize,grid);let version=0,noteTimer=0;
        const labels={clock:'Clock',agenda:'Agenda',tasks:'Tasks',notes:'Quick note',focus:'Focus',storage:'Storage'};
        async function render(){const token=++version;options.replaceChildren();grid.replaceChildren();
            for(const id of OS.widgetBoard.order){options.append(toggle(labels[id],!OS.widgetBoard.hidden.includes(id),async on=>{OS.widgetBoard.hidden=on?OS.widgetBoard.hidden.filter(x=>x!==id):[...OS.widgetBoard.hidden,id];await saveWidgets();}));
                if(OS.widgetBoard.hidden.includes(id))continue;
                const card=OS.el('section',{class:'suite-card widget-tile','data-widget':id}),body=OS.el('div',{class:'widget-content'}),header=OS.el('div',{class:'suite-card-header'},OS.el('h2',{text:labels[id]}));
                for(const [direction,step]of [['up',-1],['down',1]])header.append(icon(direction,`Move ${labels[id]} ${direction}`,async()=>{const order=OS.widgetBoard.order,index=order.indexOf(id),next=index+step;if(next>=0&&next<order.length){[order[index],order[next]]=[order[next],order[index]];await saveWidgets();}}));
                card.append(header,body);grid.append(card);
                if(id==='clock'){body.append(OS.el('div',{class:'widget-time',text:OS.time()}),note(new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})));}
                if(id==='notes'){const input=OS.el('textarea',{'aria-label':'Widget quick note',placeholder:'Keep a thought here…',maxlength:20000});input.value=OS.widgetBoard.note;input.oninput=()=>{OS.widgetBoard.note=input.value;clearTimeout(noteTimer);noteTimer=setTimeout(()=>OS.featureSave('widget-board',OS.widgetBoard).catch(console.warn),250);};body.append(input);}
                if(id==='agenda'){const events=await OS.db.get('calendarEvents')||[];if(token!==version||w.closed)return;const upcoming=events.filter(e=>e.date>=OS.isoDate(new Date())).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).slice(0,5);for(const event of upcoming)body.append(button(`${event.date} · ${event.time} · ${event.title}`,()=>OS.openApp('calendar',{date:event.date})));if(!upcoming.length)body.append(note('Nothing scheduled yet.'));body.append(button('Open Calendar',()=>OS.openApp('calendar')));}
                if(id==='tasks'){const tasks=await OS.db.get('tasks')||[];if(token!==version||w.closed)return;for(const task of tasks.filter(t=>!t.done).slice(0,5))body.append(toggle(task.title,false,async done=>{const fresh=await OS.db.get('tasks')||[],found=fresh.find(t=>t.id===task.id);if(found){found.done=done;await OS.db.set('tasks',fresh);OS.emit('tasks-change');}}));if(tasks.every(t=>t.done))body.append(note('Your task list is clear.'));body.append(button('Open Tasks',()=>OS.openApp('tasks')));}
                if(id==='focus')body.append(OS.el('strong',{class:'widget-focus'}),button('Open Focus',()=>OS.openApp('focus')));
                if(id==='storage'){const data=await OS.storageSense.scan();if(token!==version||w.closed)return;body.append(OS.el('strong',{class:'widget-metric',text:OS.formatBytes(data.bytes)}),note(`${data.entries.filter(e=>e.kind==='file').length} virtual files`),button('Manage storage',()=>OS.openApp('storage')));}
            }tick();}
        function tick(){const clock=$('.widget-time',grid);if(clock)clock.textContent=OS.time();const f=$('.widget-focus',grid);if(f)f.textContent=`${Math.round(OS.focusSession.today())} minutes today · ${OS.focusSession.state.status}`;}
        w.on('focus-tick',tick);w.on('feature-change',e=>{if(e.name==='widgets')OS.guard(render)();});for(const name of ['tasks-change','calendar-change'])w.on(name,()=>OS.guard(render)());
        w.addCleanup(()=>{version++;clearTimeout(noteTimer);OS.featureSave('widget-board',OS.widgetBoard).catch(console.warn);});return render();
    }});
    OS.register('workspaces',{title:'Window Groups',icon:'taskview',color:'blue',category:'System',description:'Arrange windows, save reusable snap groups, and personalize virtual desktops.',width:940,height:710,singleton:true,mount(w){
        const root=page(w,'A place for every project','Save app locations as named window groups. Restoring reuses compatible open windows without closing documents. Layouts contain paths and positions, not unsaved document contents.'),arrange=OS.el('div',{class:'suite-card'}),windows=OS.el('div',{class:'suite-checks'}),selected=new Set(),groups=OS.el('div',{class:'suite-list'}),desktops=OS.el('div',{class:'suite-list'});
        const arrangeActions=OS.el('div',{class:'suite-actions'});for(const [id,label]of [['columns','Columns'],['grid','Grid'],['primary','Primary + stack']])arrangeActions.append(button(label,()=>{if(!selected.size)throw Error('Select one to four windows.');OS.workspaces.arrange(id,[...selected]);}));
        arrange.append(OS.el('h2',{text:'Arrange open windows'}),note('Choose up to four windows. Small panes may require scrolling inside an app.'),windows,arrangeActions,button('Save current group',async()=>{const name=await OS.prompt('Save window group','My workspace');if(name!==null){await OS.workspaces.save(name);renderGroups();}},true));
        root.append(arrange,OS.el('h2',{text:'Saved window groups'}),groups,OS.el('h2',{text:'Virtual desktops'}),button('New desktop',async()=>{if(OS.desktops.length>=12)throw Error('Desktop limit reached (12).');await OS.addDesktop();renderDesktops();}),desktops);
        function renderWindows(){windows.replaceChildren();for(const win of OS.windows.values())if(win.id!==w.id&&!win.closed){windows.append(toggle(win.title,selected.has(win.id),on=>{if(on&&selected.size>=4)throw Error('Select at most four windows.');on?selected.add(win.id):selected.delete(win.id);}));}for(const id of selected)if(!OS.windows.has(id))selected.delete(id);}
        function renderGroups(){groups.replaceChildren();if(!OS.workspaces.groups.length)groups.append(note('No saved groups. Arrange some apps, then save their layout.'));for(const group of OS.workspaces.groups){const row=OS.el('div',{class:'suite-card suite-actions'},OS.el('strong',{class:'grow',text:`${group.name} · ${group.entries.length} apps`}));row.append(button('Restore group',()=>OS.workspaces.restore(group.id),true),button('Rename',async()=>{const name=await OS.prompt('Rename window group',group.name);if(name?.trim()){group.name=name.trim().slice(0,60);await OS.workspaces.persist();renderGroups();}}),button('Remove',async()=>{if(await OS.confirm('Remove saved group?','This removes the saved layout only; open windows and files are kept.','Remove')){OS.workspaces.groups=OS.workspaces.groups.filter(g=>g.id!==group.id);await OS.workspaces.persist();renderGroups();}}));groups.append(row);}}
        async function saveDesktops(){await OS.db.set('desktops',OS.desktops);OS.renderer?.invalidate();OS.emit('windows');renderDesktops();}
        function renderDesktops(){desktops.replaceChildren();for(const desk of OS.desktops){const row=OS.el('div',{class:'suite-card desktop-setting'}),title=button(desk.name+ (desk.id===OS.activeDesktop?' · Active':''),()=>{OS.switchDesktop(desk.id);renderDesktops();});row.append(title,button('Rename',async()=>{const name=await OS.prompt('Rename desktop',desk.name);if(name?.trim()){desk.name=name.trim().slice(0,40);await saveDesktops();}}),select('Wallpaper for '+desk.name,[['','Use global background'],['bloom','Bloom'],['midnight','Midnight'],['dusk','Dusk'],['sage','Sage']],desk.wallpaper||'',async value=>{desk.wallpaper=value;await saveDesktops();}),icon('up','Move desktop earlier',async()=>{const i=OS.desktops.indexOf(desk);if(i>0){[OS.desktops[i],OS.desktops[i-1]]=[OS.desktops[i-1],OS.desktops[i]];await saveDesktops();}}),button('Remove desktop',async()=>{if(OS.desktops.length===1)throw Error('Keep at least one desktop.');if(!await OS.confirm('Remove '+desk.name+'?','Its windows move to the first remaining desktop. No apps are closed.','Remove'))return;const target=OS.desktops.find(d=>d.id!==desk.id);for(const win of OS.windows.values())if(win.desktop===desk.id){win.desktop=target.id;win.sync();}OS.desktops=OS.desktops.filter(d=>d.id!==desk.id);if(OS.activeDesktop===desk.id)OS.switchDesktop(target.id);await saveDesktops();}));desktops.append(row);}}
        w.on('windows',()=>{renderWindows();renderDesktops();});w.on('feature-change',e=>{if(e.name==='workspaces')renderGroups();});renderWindows();renderGroups();renderDesktops();
    }});
    OS.register('history',{title:'File History',icon:'undo',color:'blue',category:'System',description:'Preview, download, and restore previous versions of virtual files.',width:840,height:665,async mount(w,options){
        const root=page(w,'A way back','Aster saves previous versions when virtual files are overwritten. Up to 10 per path, 200 total, 32 MiB retained; files over 8 MiB are skipped. This is same-browser recovery, not an external backup.'),search=OS.el('input',{'aria-label':'Filter file history',placeholder:'Filter by path',value:options.path||''}),list=OS.el('div',{class:'suite-list'});
        root.append(toggle('Keep file history',OS.settings.historyEnabled,on=>OS.setSetting('historyEnabled',on)),search,list);search.oninput=OS.guard(render);
        async function render(){const rows=await OS.history.list();if(w.closed)return;list.replaceChildren();for(const version of rows.filter(e=>e.path.toLowerCase().includes(search.value.toLowerCase()))){const row=OS.el('div',{class:'suite-card'},OS.el('strong',{text:version.path}),note(`${new Date(version.time).toLocaleString()} · ${OS.formatBytes(version.size)}`)),actions=OS.el('div',{class:'suite-actions'});
                actions.append(button('Preview',async()=>{const entry=await OS.history.get(version.id);if(!entry)throw Error('Version expired.');const blob=new Blob([entry.content],{type:entry.mime});const preview=OS.el('pre',{class:'history-preview',text:/^text\/|json/.test(entry.mime)?(await blob.slice(0,100000).text()):'Binary file. Download this version to inspect it.'});await OS.dialog({title:OS.fs.name(entry.path)+' — previous version',message:'Preview limited to 100 KiB. No content is executed.',extra:preview,confirm:'Done'});}),button('Restore copy',async()=>{const path=await OS.history.restore(version.id,true);OS.notify('Version restored',path);}),button('Restore original',async()=>{if(await OS.confirm('Restore previous version?','The current file will be saved in history before replacement. Unsaved editor buffers are not changed.','Restore')){await OS.history.restore(version.id);await render();}}),button('Download',async()=>{const entry=await OS.history.get(version.id);if(entry)OS.download(new Blob([entry.content],{type:entry.mime}),OS.fs.name(entry.path));}));row.append(actions);list.append(row);}
            if(!list.childElementCount)list.append(note('No retained versions match. Save an edited virtual file to create its first previous version.'));}
        w.on('fs-change',()=>OS.guard(render)());w.on('feature-change',e=>{if(e.name==='history')OS.guard(render)();});await render();
    }});
    OS.register('storage',{title:'Storage Manager',icon:'folder',color:'gold',category:'System',description:'Actual storage usage, large files, safe Recycle Bin cleanup and Storage Sense.',width:850,height:720,singleton:true,mount(w){
        const root=page(w,'Room for what’s next','Storage Sense only removes aged items already in Aster’s virtual Recycle Bin. It never cleans Downloads, connected local folders, Win32 drives, or other web apps.'),content=OS.el('div');root.append(content);
        async function render(){const data=await OS.storageSense.scan();if(w.closed)return;content.replaceChildren();const policy=OS.storageSense.policy,summary=OS.el('div',{class:'suite-card'});summary.append(OS.el('h2',{text:OS.formatBytes(data.bytes)+' in virtual files'}),note(`${OS.formatBytes(data.historyBytes)} in previous versions. ${data.estimate.quota?'Shared-origin browser quota: '+OS.formatBytes(data.estimate.quota)+'; total origin usage: '+OS.formatBytes(data.estimate.usage||0):'The browser does not expose a storage estimate.'}`));for(const [name,bytes]of data.groups)summary.append(OS.el('div',{class:'storage-usage-row'},OS.el('span',{text:name}),OS.el('progress',{max:Math.max(1,data.bytes),value:bytes,'aria-label':name+' usage'}),OS.el('span',{text:OS.formatBytes(bytes)})));content.append(summary);
            const days=select('Recycle Bin retention',[[1,'1 day'],[7,'7 days'],[30,'30 days'],[90,'90 days']],policy.days,async value=>{policy.days=Number(value);await OS.featureSave('storage-sense',policy);});
            content.append(OS.el('h2',{text:'Storage Sense'}),toggle('Clean aged Recycle Bin items on startup',policy.enabled,async on=>{policy.enabled=on;await OS.featureSave('storage-sense',policy);}),field('Retain deleted items for at least',days),note('Automatic cleanup is opt-in and runs at most once per day when Aster starts. It does not run after the browser closes.'),button('Review cleanup',async()=>{const fresh=await OS.storageSense.scan(),roots=OS.storageSense.eligible(fresh.entries);const bytes=fresh.entries.filter(e=>roots.some(r=>e.path===r.path||e.path.startsWith(r.path+'/'))).reduce((n,e)=>n+(e.size||0),0);if(!roots.length){OS.notify('Nothing eligible','No Recycle Bin items are old enough.');return;}if(await OS.confirm('Delete aged Recycle Bin items?',`${roots.length} items · ${OS.formatBytes(bytes)}. Only these already-deleted virtual items are removed permanently.`, 'Delete permanently',true)){await OS.storageSense.clean(policy.days,roots);await render();}},true));
            content.append(OS.el('h2',{text:'Largest virtual files'}));for(const f of data.entries.filter(e=>e.kind==='file'&&!e.path.startsWith('/.')).sort((a,b)=>(b.size||0)-(a.size||0)).slice(0,8))content.append(OS.el('div',{class:'suite-card suite-actions'},OS.el('span',{class:'grow',text:f.path}),OS.el('span',{text:OS.formatBytes(f.size)}),button('Show folder',()=>OS.openApp('files',{path:OS.fs.parent(f.path)}))));
            content.append(OS.el('h2',{text:'Recovery & backup'}),OS.el('div',{class:'suite-actions'},button('File History',()=>OS.openApp('history')),button('Clear version history',async()=>{if(await OS.confirm('Delete all previous versions?','Current virtual files are kept, but previous versions can no longer be restored.','Delete history',true)){await OS.history.clear();await render();}}),button('Export backup',()=>OS.exportBackup()),button('Storage settings',()=>OS.openApp('settings',{section:'storage'}))));}
        if(OS.storageSense.error)root.append(note('Automatic cleanup did not complete: '+OS.storageSense.error));w.on('fs-change',()=>OS.guard(render)());return render();
    }});
    OS.register('archives',{title:'ZIP Archives',icon:'folder',color:'gold',category:'Utilities',description:'Create, inspect and safely extract standard ZIP files in the virtual drive.',width:800,height:650,async mount(w,options){
        const root=page(w,'ZIP archives','Create compressed ZIP files and inspect or extract stored/DEFLATE ZIPs. Processing is local. Encrypted, ZIP64, unsafe paths and files beyond the 64 MiB expanded limit are rejected.'),actions=OS.el('div',{class:'suite-actions'}),content=OS.el('div',{class:'suite-list'});let path=options.path||'',busy=false;
        actions.append(button('Import ZIP',async()=>{const [file]=await OS.readFile('.zip,application/zip');if(!file)return;if(file.size>AsterZIP.LIMIT+1024*1024)throw Error('ZIP is too large.');path=await OS.fs.unique('/Downloads/'+file.name);await OS.fs.write(path,file,'application/zip');await render();}),button('Create ZIP from virtual files',async()=>{const files=(await OS.db.all()).filter(e=>e.kind==='file'&&!e.path.startsWith('/.')),selected=new Set(),extra=OS.el('div',{class:'archive-picker'});for(const f of files)extra.append(toggle(f.path,false,on=>on?selected.add(f.path):selected.delete(f.path)));if(await OS.dialog({title:'Choose virtual files',message:'Original files stay unchanged.',extra,confirm:'Next'})){const name=await OS.prompt('ZIP file name','Archive.zip');if(name?.trim()){OS.fs.validateName(name);path=await OS.archives.create([...selected],'/Downloads/'+(name.endsWith('.zip')?name:name+'.zip'));await render();}}}),button('Refresh',()=>render()));root.append(actions,content);
        async function render(){content.replaceChildren();if(!path){const rows=(await OS.db.all()).filter(e=>/\.zip$/i.test(e.path)&&!e.path.startsWith('/.'));if(!rows.length)content.append(note('No ZIP files yet. Import one, create one here, or select items in File Explorer → More → Create ZIP.'));for(const e of rows)content.append(button(e.path,async()=>{path=e.path;await render();}));return;}
            const file=await OS.fs.read(path);if(file.size>AsterZIP.LIMIT+1024*1024)throw Error('ZIP is too large.');const parsed=AsterZIP.inspect(await(await OS.fs.blob(file)).arrayBuffer());if(w.closed)return;
            content.append(OS.el('h2',{text:OS.fs.name(path)}),note(`${parsed.entries.length} entries · ${OS.formatBytes(parsed.total)} expanded. CRC checks are performed before extraction commits any files.`),OS.el('div',{class:'suite-actions'},button('Extract to Downloads',async()=>{if(busy)return;busy=true;try{const folder=await OS.archives.extract(path,'/Downloads');OS.notify('Archive extracted',folder);OS.openApp('files',{path:folder});}finally{busy=false;}},true),button('Download ZIP',async()=>OS.download(await OS.fs.blob(file),OS.fs.name(path))),button('All archives',async()=>{path='';await render();})));
            for(const e of parsed.entries)content.append(OS.el('div',{class:'archive-row'},OS.el('span',{text:e.name}),OS.el('small',{text:e.directory?'Folder':OS.formatBytes(e.length)})));}
        await render();
    }});
})();
