/* Clipboard utilities and input preferences; all content remains text or a PNG Blob. MIT. */
'use strict';
(() => {
    const OS=Aster,C=OS.clipboardTools,M=AsterInputModels;
    const button=(text,fn,primary=false)=>OS.el('button',{type:'button',class:primary?'primary':'secondary',text,onclick:OS.guard(fn)});
    const note=text=>OS.el('p',{class:'integration-note',text});
    const field=(label,node)=>OS.el('label',{class:'suite-field'},OS.el('span',{text:label}),node);
    OS.showClipboardUtilities=()=>{C.remember();return OS.launch('clipboard-tools');};
    OS.clipboardSettings=(main)=>{
        main.append(OS.el('h2',{text:'Clipboard & keyboard'}),note('Native copy and paste work without history. Settings affect Aster only, not your operating system or the browser’s permission controls.'));
        function toggle(key,label,help){const input=OS.el('input',{type:'checkbox',role:'switch','aria-label':label,checked:!!OS.settings[key]});input.onchange=OS.guard(()=>OS.input.configure({[key]:input.checked}));main.append(OS.el('div',{class:'clipboard-setting'},OS.el('label',{},input,OS.el('strong',{text:label})),note(help)));}
        function select(key,label,choices,help){const node=OS.el('select',{'aria-label':label});for(const [value,text]of choices)node.append(OS.el('option',{value,text,selected:String(value)===String(OS.settings[key])}));node.onchange=OS.guard(()=>OS.input.configure({[key]:typeof M.DEFAULTS[key]==='number'?Number(node.value):node.value}));main.append(OS.el('div',{class:'clipboard-setting'},field(label,node),note(help)));}
        select('keyboardProfile','Keyboard profile',[['auto','Automatic — '+OS.input.platform()],['windows','Windows / Control'],['macos','macOS / Command'],['linux','Linux / Control']],'Keyboard behavior follows the host platform, never the selected visual theme. Native editing and input composition always take priority.');
        toggle('shellShortcuts','Enable desktop shortcuts','Turn off Aster launch shortcuts while retaining app-local editing, menus and native browser shortcuts.');
        select('superShortcuts','Super / Windows-key shortcuts',[['auto','Automatic (off on macOS)'],['off','Off'],['on','On outside text fields']],'The real OS may reserve these keys. Command editing chords are not intercepted in text fields.');
        select('clipboardShortcut','Clipboard history shortcut',[['Ctrl+Alt+V','Ctrl + Alt + V'],['Ctrl+Shift+H','Ctrl + Shift + H'],['Meta+Alt+H','Command / Super + Alt + H'],['none','No keyboard shortcut']],'AltGr is never treated as Ctrl+Alt. Use Clipboard utilities from Start when the OS reserves a shortcut.');
        toggle('clipboardHistory','Clipboard history','Opt in to capture copied/cut text in supported Aster fields. Password, one-time-code, payment and private fields are excluded.');
        toggle('clipboardCapturePaste','Include pasted text in history','Off by default. Captures text from explicit native paste events in Aster fields, not other applications or inaccessible frames.');
        select('clipboardLimit','History capacity',[[10,'10 items'],[25,'25 items'],[50,'50 items'],[100,'100 items']],'Each snippet is limited to 16,384 characters. Reducing the capacity removes excess items, unpinned first.');
        select('clipboardExpire','Expire unpinned history',[[0,'At page reload'],[15,'After 15 minutes'],[60,'After 1 hour'],[1440,'After 24 hours']],'Pinned snippets do not expire. Unpinned items are never written to disk.');
        toggle('clipboardPersistPins','Keep pinned snippets after reload','Pinned text is stored unencrypted in this browser. Turning this off erases stored pins but keeps the in-memory list. Export only when you intend to share its contents.');
        toggle('clipboardClearOnLock','Clear temporary clipboard data on Aster lock','Clears unpinned snippets, the workbench preview, and saved insertion targets. Does not clear your operating-system clipboard.');
        toggle('clipboardPlainPaste','Paste plain text in rich Aster fields','Removes formatting when Aster handles a paste into its contenteditable fields. Native inputs are unchanged.');
        toggle('clipboardBridge','Enable embedded app clipboard helpers','Cooperating apps can request plain text through AsterClipboard. Every read/write still requires a separate visible confirmation. Native keyboard paste does not need this helper.');
        toggle('editorTabFocus','Tab moves focus in text editors','Use normal keyboard focus navigation instead of indentation/completion in Notepad, Code Studio and Terminal.');
        toggle('terminalPasteGuard','Confirm multiline terminal paste','Aster Terminal does not execute pasted commands automatically. Multiline/control-character pastes require review.');
        const status=OS.el('p',{role:'status',class:'integration-note'});
        main.append(OS.el('div',{class:'suite-actions'},button('Open clipboard history',()=>OS.showClipboard()),button('Open clipboard utilities',OS.showClipboardUtilities),button('Clear system clipboard',async()=>{if(await OS.confirm('Clear your system clipboard?','Replace its current contents with empty text. Other applications will see this change. Aster snippets are kept.','Clear system clipboard'))await C.copyText('',{history:false});}),button('Check browser support',async()=>{
            const caps={secure:globalThis.isSecureContext,read:!!navigator.clipboard?.readText,write:!!navigator.clipboard?.writeText,image:!!navigator.clipboard?.write&&!!globalThis.ClipboardItem};const labels=[];
            for(const key of ['clipboard-read','clipboard-write']){try{labels.push(key+': '+(await navigator.permissions.query({name:key})).state);}catch{labels.push(key+': browser does not expose a permission query');}}
            status.textContent=`${caps.secure?'Secure context':'Non-secure context'} · read text: ${caps.read?'supported':'unavailable'} · write text: ${caps.write?'supported':'unavailable'} · image writing: ${caps.image?'supported':'unavailable'}. ${labels.join('. ')}. Native keyboard paste remains available independently.`;
        }),button('Delete all clipboard data',async()=>{if(await OS.confirm('Delete clipboard history?','Delete every saved snippet including pinned entries and clear the temporary preview. The OS clipboard is not changed.','Delete all',true))await C.clear(true);})),status);
    };
    OS.register('clipboard-tools',{title:'Clipboard Utilities',icon:'paste',color:'blue',category:'Utilities',description:'Native clipboard tools, text transformations, images, snippets and keyboard configuration.',width:940,height:740,minWidth:350,singleton:true,mount(w){
        C.remember();const root=OS.el('div',{class:'suite-app clipboard-tools','data-clipboard-ui':'true'}),head=OS.el('header',{class:'suite-heading'},OS.el('span',{class:'eyebrow',text:'ASTER / CLIPBOARD'}),OS.el('h1',{text:'Clipboard utilities'}),note('Read only on request. Paste with your keyboard or browser menu; no clipboard history is needed.'));
        const tabs=OS.el('div',{class:'suite-actions',role:'tablist','aria-label':'Clipboard utilities views'}),panels=OS.el('div');root.append(head,tabs,panels);w.body.append(root);let objectURL=null;
        const work=OS.el('section',{role:'tabpanel','aria-label':'Clipboard workbench'}),history=OS.el('section',{role:'tabpanel','aria-label':'Clipboard snippets',hidden:true}),settings=OS.el('section',{role:'tabpanel','aria-label':'Clipboard configuration',hidden:true});
        const tabNodes=[];for(const [name,panel]of [['Workbench',work],['Snippets',history],['Configuration',settings]]){const b=button(name,()=>{for(const [i,p]of [work,history,settings].entries()){p.hidden=p!==panel;tabNodes[i].setAttribute('aria-selected',String(p===panel));tabNodes[i].tabIndex=p===panel?0:-1;}if(panel===history)renderHistory();if(panel===settings){settings.replaceChildren();OS.clipboardSettings(settings);}});b.setAttribute('role','tab');b.setAttribute('aria-selected',String(panel===work));b.tabIndex=panel===work?0:-1;tabNodes.push(b);tabs.append(b);}
        tabs.onkeydown=e=>{if(M.blocked(e))return;const i=tabNodes.indexOf(document.activeElement);if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const n=e.key==='Home'?0:e.key==='End'?2:(i+(e.key==='ArrowLeft'?2:1))%3;tabNodes[n].click();tabNodes[n].focus();}};
        panels.append(work,history,settings);
        const status=OS.el('p',{role:'status',class:'clipboard-status',text:'System clipboard has not been read.'}),text=OS.el('textarea',{'aria-label':'Clipboard text',rows:7,'data-private':'true',spellcheck:false}),types=OS.el('p',{class:'integration-note'}),image=OS.el('img',{alt:'Clipboard PNG preview',hidden:true,class:'clipboard-image'}),html=OS.el('pre',{class:'clipboard-html',hidden:true});
        const format=OS.el('select',{'aria-label':'Text transformation'});for(const [v,t]of [['plain','Keep original text'],['trim','Trim edges'],['line','Single line'],['upper','UPPERCASE'],['lower','lowercase'],['lf','Normalize line endings']])format.append(OS.el('option',{value:v,text:t}));
        async function run(fn,success){status.textContent='Working…';try{await fn();status.textContent=success;}catch(e){status.textContent=e.message+' Use the native Paste command in the text box as a fallback.';}}
        text.addEventListener('paste',e=>{if(!e.clipboardData||e.defaultPrevented)return;const data=e.clipboardData,files=[...data.files],png=files.find(f=>f.type==='image/png');const snap={text:data.getData('text/plain'),html:data.getData('text/html'),image:png&&png.size<=M.LIMITS.image?png:null,types:[...data.types]};if(snap.text.length>M.LIMITS.text||snap.html.length>M.LIMITS.text){e.preventDefault();status.textContent='Clipboard text exceeds 1 Mi characters.';return;}queueMicrotask(()=>{snap.text=text.value;C.setCurrent(snap);status.textContent='Captured from your explicit Paste action.';});});
        const actions=OS.el('div',{class:'suite-actions'},button('Read system clipboard',()=>run(()=>C.inspect(),'Clipboard read. Select a format or copy the edited text.'),true),button('Manual paste…',()=>C.manualPaste(null)),button('Copy text',()=>run(()=>C.copyText(text.value),'Text copied to your system clipboard.')),button('Paste into previous field',()=>run(()=>C.insert(M.transform(text.value,format.value)),'Text inserted into the original field.')),button('Save snippet',async()=>{if(!OS.settings.clipboardHistory){status.textContent='Enable clipboard history in Configuration to save snippets.';return;}const entry=await C.add(text.value);status.textContent=entry?'Snippet saved.':'Snippet could not be saved: empty, too long, or all history slots are pinned.';}));
        work.append(actions,status,field('Text — edit or paste here',text),OS.el('div',{class:'suite-actions'},format,button('Transform text',()=>{text.value=M.transform(text.value,format.value);status.textContent='Transformed in the workbench only.';}),button('Download text',()=>OS.download(new Blob([text.value],{type:'text/plain;charset=utf-8'}),'Clipboard.txt')),button('Clear preview',()=>{text.value='';C.setCurrent(null);status.textContent='Temporary preview cleared. OS clipboard is unchanged.';})),types,image,html,OS.el('div',{class:'suite-actions'},button('Copy PNG image',()=>run(()=>C.copyImage(),'PNG image copied.')),button('Download image',()=>{if(!C.current?.image)throw Error('Paste or read a PNG image first.');OS.download(C.current.image,'Clipboard.png');}),button('Save image to Pictures',async()=>{if(!C.current?.image)throw Error('Paste or read a PNG image first.');const paths=await C.importFiles([new File([C.current.image],'Clipboard.png',{type:'image/png'})],'/Pictures');status.textContent='Saved '+paths[0];})));
        function preview(){if(objectURL){URL.revokeObjectURL(objectURL);objectURL=null;}const current=C.current;text.value=current?.text||'';types.textContent=current?'Available representations: '+current.types.join(', '):'No current preview';image.hidden=!current?.image;if(current?.image){objectURL=URL.createObjectURL(current.image);image.src=objectURL;}else image.removeAttribute('src');html.hidden=!current?.html;html.textContent=current?.html?'HTML source (inert, never executed):\n'+current.html:'';}
        const search=OS.el('input',{type:'search','aria-label':'Search snippets',placeholder:'Search snippets'}),list=OS.el('div',{class:'suite-list'});
        history.append(OS.el('div',{class:'suite-actions'},button('Add snippet',()=>edit()),button('Export snippets',async()=>{if(await OS.confirm('Export clipboard snippets?','The exported JSON contains the text of all retained snippets. Keep it private.','Export'))await C.export();}),button('Import snippets',async()=>{const [f]=await OS.readFile('.json,application/json');if(!f)return;if(f.size>M.LIMITS.package)throw Error('Snippet package exceeds 2 MiB.');const value=JSON.parse(await f.text()),rows=M.unpack(value);if(await OS.confirm('Import clipboard snippets?',rows.length+' snippets will be merged as plain text. Nothing is executed.','Import'))await C.import(value);}),button('Clear unpinned',()=>{C.model.clear();return C.save();})),search,list);search.oninput=renderHistory;
        async function edit(entry){const input=OS.el('textarea',{'aria-label':'Snippet text',rows:6,maxlength:M.LIMITS.historyText,'data-private':'true'});input.value=entry?.text||'';const result=await OS.dialog({title:entry?'Edit snippet':'Add snippet',message:'Plain text, up to 16,384 characters. Turn on history before saving.',extra:input,confirm:'Save'});if(!result)return;if(!OS.settings.clipboardHistory)throw Error('Turn on clipboard history in Configuration first.');if(entry)C.model.edit(entry.id,input.value);else if(!C.model.add(input.value))throw Error('Cannot save an empty or oversized snippet, or exceed pinned capacity.');await C.save();}
        function renderHistory(){list.replaceChildren();if(!OS.settings.clipboardHistory){list.append(note('History is off. Enable it in Configuration. Workbench copy and paste work without history.'));return;}const rows=C.model.prune().filter(e=>e.text.toLocaleLowerCase().includes(search.value.toLocaleLowerCase()));if(!rows.length)list.append(note('No retained snippets match.'));for(const e of rows){const card=OS.el('article',{class:'suite-card'},OS.el('pre',{class:'clipboard-snippet',text:e.text}),OS.el('small',{text:(e.pinned?'Pinned':'Session only')+' · '+e.text.length+' characters'}));card.append(OS.el('div',{class:'suite-actions'},button('Paste',()=>C.paste(e.id),true),button('Copy',()=>C.copyText(e.text)),button('Edit',()=>edit(e)),button(e.pinned?'Unpin':'Pin',()=>{C.model.pin(e.id);return C.save();}),button('Delete',()=>{C.model.remove(e.id);return C.save();})));list.append(card);}}
        w.on('feature-change',e=>{if(e.name==='clipboard')renderHistory();if(e.name==='clipboard-current')preview();});w.addCleanup(()=>{if(objectURL)URL.revokeObjectURL(objectURL);});preview();renderHistory();
    }});
})();
